
[#PaymentPageSolutions_PPv2_EPP_NVP]
== Merchants Integrated with NVP (EPP)

[#PaymentPageSolutions_PPv2_EPP_NVP_Migrating]
=== Migrating to {payment-page-v2-abbr}

In addition to the new backend-to-backend JSON flow, {payment-page-v2-abbr} supports an
updated NVP flow for merchants who already integrated one of the Payment
Page solutions previously and do not want to switch.

In that case, the migration to {payment-page-v2-abbr} requires only a few minor
changes. New features have an NVP field equivalent so you can use them
in your integration. Check the <<PPv2_Features, {payment-page-v2-abbr} Features>> section for specifics.

NOTE: Contact <<ContactUs, merchant support>> for your production credentials.

. Find the ``paymentPageLoader`` JavaScript library in
your ``<head>`` HTML code:
+
[source,html,subs=attributes+]
----
<script src="https://{test-instance-hostname}/engine/hpp/paymentPageLoader.js" type="text/javascript"></script>
----
+
Replace it with:
+
[source,html,subs=attributes+]
----
<script src="https://{pp-test-instance-hostname}/loader/paymentPage.js" type="text/javascript"></script>
----
+
. Find the ``embeddedPay`` function call at the end of your ``Pay button`` function:
+
[source,js,subs=attributes+]
----
{payment-page-function}.embeddedPay(requestData);
----
+
Replace it with:
+
[source,js,subs=attributes+]
----
{payment-page-function-short}.embeddedPay(requestData);
----
+
The fields in ``requestData`` remain the same and no changes are needed.

//-
