[#PPv2_Features_LimitCardBrands]
== Limit Credit Card Brands

Use the _Limit Credit Card Brands_ option to display your preferred credit card brands. Display, for example, a different set of credit card brands to consumers in different regions in the world. 

This option is available for all of our _{payment-page-v2}_ ({payment-page-v2-abbr}) integration options:

* the <<PaymentPageSolutions_PPv2_HPP, _Hosted Payment Page_>> (HPP), 
* the <<PaymentPageSolutions_PPv2_EPP, _Embedded Payment Page_>> (EPP) or 
* the <<PPv2_Seamless, Seamless>> integration. 

//-

.Configure the _Limit Credit Card Brands_ Option

. Include the ``credit-card-brand-filter`` array in the payment request.
. Add the credit card brand names to the JSON array in your preferred order. Separate the credit card brand names with a comma. 
. As a result, {payment-page-v2-abbr} displays only the credit card brands you added to the array.

//-

NOTE: See our supported <<AppendixD, credit card brands>>. 

The _Limit Credit Card Brands_ option is available in JSON only. You can send the _Limit Credit Card Brands_ option with each request. 

[cols="v,,,"]
[%autowidth]
|===
| Field | Data Type | Parent |Description

| ``credit-card-brand-filter`` 
| Array 
| options (\{ }) 
| Displays the credit card brands specified in this field.
|===

//-

.Example Request

Use the test credentials we provide for <<PPv2_CC_TestCredentials, _Credit Card_>> and send the sample below. +

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_FeaturesLimitCardbrandConfiguringLimitCardbrand_ExampleRequestLimitCardbrand.json[]
----

//-