[#MobilePaymentSDK_Android_MB_Referencia]
---
== *MB Referencia*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.PENDING_DEBIT`* - represents the request for a debit. If the [Transaction State] is success, then the outcome of the debit is not yet known. A further [Transaction Type] of debit follows, whose [Transaction State] indicates the outcome. If the [Transaction State] of the pending-debit is failed, then the request has not been processed.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/mbreferencia.aar')
    ...
}
----

When adding/removing this feature, perform a full clean build.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple MB Referencia Payment

This is a code example for a basic MB Referencia payment:

[source,kotlin]
----
val mbReferenciaPayment = MbreferenciaPayment(
        signature = signature
        requestID = requestID
        merchantAccountId = merchantAccountId
        transactionType = transactionType
        amount = amount
        currency = currency,
        descriptor = descriptor
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(mbReferenciaPayment)
----

[source,java]
----
mbReferenciaPayment = new MbreferenciaPayment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantId)
        .setRequestId(requestId)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .setDescriptor(descriptor)
        .build();

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(mbReferenciaPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`sdkpay_ecom_color_main`* - color tint for progress bar

==== Customizing MB Referencia Payments

*Color Resources*

1 - `sdkpay_ecom_color_main`
