[#MobilePaymentSDK_Android_Google_Pay]
---
== *Google Pay*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.AUTHORIZATION_ONLY`* - verifies the validity of account holder’s card, but does not leave an authorized amount.

*`TransactionType.PURCHASE`* - takes funds from the [Card Holder]'s account. A one-step process to conduct two Transaction Types: [Authorization] and [Capture]..

*`TransactionType.REFERENCED_PURCHASE`* - takes funds from the [Card Holder]'s account. Identical to a [Purchase] except for the fact that it refers to a previous [Purchase] transaction.

*`TransactionType.REFERENCED_AUTHORIZATION`* - places the account holder’s funds on hold. Identical to a [Purchase] except for the fact that it refers to a previous [Purchase] transaction.

*`TransactionType.TOKENIZE`* - Provides a unique [Card Token] from sensitive Credit Card Data. The [Card Token] can be used in subsequent transactions instead of the card information itself.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/google-pay.aar')
    ...
}
----

When adding/removing this feature, perform a full clean build.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple Google Pay Payment

This is a code example for a basic Google Pay payment:

[source,kotlin]
----
val googlePayPayment = GooglePayPayment(
        signature = signature
        requestID = requestID
        merchantAccountId = merchantAccountId
        transactionType = transactionType
        amount = amount
        currency = currency,
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(googlePayPayment)
----

[source,java]
----
googlePayPayment = new GooglePayPayment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantId)
        .setRequestId(requestId)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .build();

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(googlePayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`sdkpay_ecom_color_main`* - color tint for progress bar

==== Customizing Google Pay Payments

*Color Resources*

1 - `sdkpay_ecom_color_main`
