[#MobilePaymentSDK_Android_PayPal]
---
== *PayPal*
---

=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---

This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.AUTHORIZATION_ONLY`* - verifies the validity of account holder’s card, but does not leave an authorized amount.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

=== Module Dependency

Edit your `build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/paypal.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Basic PayPal Payment

PayPal requires additional setup of the `sdkpay_ecom_paypal_scheme` and
`sdkpay_ecom_paypal_host` resources so you can receive responses from
PayPal:

[source,xml]
----
<resources>
    ...
    <string name="sdkpay_ecom_paypal_scheme">yourapp</string>
    <string name="sdkpay_ecom_paypal_host">result.paypal</string>
    ...
</resources>
----

Then you can go ahead and create the payment object:

[source,kotlin]
----
val paypalPayment = PayPalPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantID,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        periodic = null,
        riskReferenceId = null
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(paypalPayment)
----

[source,java]
----
PayPalPayment payPalPayment = new PayPalPayment.Builder()
        .setSignature(signature)
        .setRequestId(requestID)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(paymentState.getAmount())
        .setCurrency(currency)
        .setPeriodic(null)
        .setRiskReferenceId(null)
        .build();

Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(paypalPayment)
----

=== Recurring PayPal Payment

On a basic level, recurring payments have two phases:

[arabic]
. The initial request, which must include:

* periodic type set to _RECURRING_,
* sequence type set to _FIRST_.

[arabic, start=2]
. The ``recurring''/follow-up requests, which must include:

* periodic type set to _RECURRING_,
* sequence type set to _SEQUENCE_,
* `parentTransactionId`and `riskReferenceId` values from the initial
request.

So in order to create a recurring payment, you need to:

[arabic]
. Send a initial request with the appropriate periodic and sequence
flags,
. Save the values of `parentTransactionId`and `riskReferenceId` fields
generated in this first payment,
. Reference these values in the follow-up request, then send it with
appropriate periodic and sequence flags.

[source,kotlin]
----
// first payment
val firstPeriodicType = Periodic()
firstPeriodicType.periodicType = PeriodicType.RECURRING.value
firstPeriodicType.sequenceType = SequenceType.FIRST.value


val firstPaypalPayment = PayPalPayment(
        signature = signature,
        requestTimeStamp = timestamp,
        requestID = requestID,
        merchantAccountId = merchantID,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        periodic = firstPeriodicType,
        riskReferenceId = null
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(firstPaypalPayment)

...
// handle first result
private var parentTransactionId: String? = null
private var riskReferenceId: String? = null

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)

    val paymentSdkResponse = data?.getSerializableExtra(Client.EXTRA_PAYMENT_SDK_RESPONSE)
    if (paymentSdkResponse is PaymentResponse) {
        parentTransactionId = paymentSdkResponse.payment?.parentTransactionId
        riskReferenceId = paymentSdkResponse.payment?.riskReferenceId
    }
}

// second payment using parentTransactionId and riskReferenceId
val secondPeriodicType = Periodic()
secondPeriodicType.periodicType = PeriodicType.RECURRING.value
secondPeriodicType.sequenceType = SequenceType.SEQUENCE.value


val secondPaypalPayment = PayPalPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantID,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        periodic = secondPeriodicType,
        riskReferenceId = null
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(secondPaypalPayment)
----

[source,java]
----
// first payment
Periodic firstPeriodicType = new Periodic();
firstPeriodicType.periodicType = PeriodicType.RECURRING.value;
firstPeriodicType.sequenceType = SequenceType.FIRST.value;


PayPalPayment firstPaypalPayment = PayPalPayment(
        signature,
        requestID,
        merchantID,
        transactionType,
        amount,
        currency,
        firstPeriodicType,
        null
);

new Client(this,"https://api-test.getneteurope.com", requestTimeout).startPayment(firstPaypalPayment);

...
// handle first result
private String parentTransactionId = null;
private String riskReferenceId = null;

protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    Serializable paymentSdkResponse = data.getSerializableExtra(Client.EXTRA_PAYMENT_SDK_RESPONSE);
    if (paymentSdkResponse instanceof PaymentResponse) {
        parentTransactionId = paymentSdkResponse.payment.getParentTransactionId();
        riskReferenceId = paymentSdkResponse.payment.getRiskReferenceId();
    }
}

// second payment using parentTransactionId and riskReferenceId;
Periodic secondPeriodicType = new Periodic();
secondPeriodicType.periodicType = PeriodicType.RECURRING.value;
secondPeriodicType.sequenceType = SequenceType.SEQUENCE.value;


PayPalPayment secondPaypalPayment = PayPalPayment(
        signature,
        requestID,
        merchantID,
        transactionType,
        amount,
        currency,
        secondPeriodicType,
        riskReferenceId
);

new Client(this, "https://api-test.getneteurope.com", requestTimeout).startPayment(secondPaypalPayment);
----