[#MobilePaymentSDK_Android_RatePay]
---
== *RatePay*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/ratepay.aar')
    ...
}
----

RatePay module contains two payment types:
RatePay Elv
RatePay Invoice

When adding/removing this feature, perform a full clean build.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple RatePay Elv Payment

This is a code example for a basic RatePay Elv payment:

[source,kotlin]
----
val ratepayPayment = RatepayElvPayment(
        signature = signature
        requestID = requestID
        merchantAccountId = merchantAccountId
        transactionType = transactionType
        amount = amount
        currency = currency
        accountHolder = accountHolder
        shippingAddress = null
        orderNumber = "132456"
        orderDetail = null
        bankAccount = BankAccount().apply{
            bankName = "Danske Bank Hamburg"
        }
        deviceFingerprint = "DeviceIdentToken"
        creditorId = "HJ45458S"
        mandateId = "458468844"
        mandateSignedDate = null
        orderItems = arrayListOf(
            OrderItem().apply {
                name = "Item 1"
                articleNumber = "123"
                this.amount = RequestedAmount("5.0", "EUR")
                taxRate = BigDecimal("0.0")
                quantity = 1
            }
        )
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(ratepayPayment)
----

[source,java]
----
ratepayPayment = new RatepayElvPayment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantId)
        .setRequestId(requestId)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .setAccountHolder(accountHolder)
        .setOrderNumber(UUID.randomUUID().toString())
        .setOrderItems(arrayListOf(
           OrderItem().apply {
               name = "Item 1"
               articleNumber = "123"
               this.amount = RequestedAmount("5.0", "EUR")
               taxRate = BigDecimal("0.0")
               quantity = 1
           }
        ))
        .setBankAccount(
            BankAccount().apply{
                bankName = "Danske Bank Hamburg"
            }
        )
        .setDeviceFingerprint("DeviceIdentToken")
        .setCreditorId("HJ45458S")
        .setMandateId("458468844")
        .build();
 
new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(ratepayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Simple RatePay Invoice Payment

This is a code example for a basic RatePay Invoice payment:

[source,kotlin]
----
val ratepayPayment = RatepayInvoicePayment(
        signature = signature
        requestID = requestID
        merchantAccountId = merchantAccountId
        transactionType = transactionType
        amount = amount
        currency = currency
        accountHolder = accountHolder
        orderNumber = "132456"
        orderDetail = null
        deviceFingerprint = "DeviceIdentToken"
        orderItems = arrayListOf(
            OrderItem().apply {
                name = "Item 1"
                articleNumber = "123"
                this.amount = RequestedAmount("5.0", "EUR")
                taxRate = BigDecimal("0.0")
                quantity = 1
            }
        )
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(ratepayPayment)
----

[source,java]
----
ratepayPayment = new RatepayInvoicePayment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantId)
        .setRequestId(requestId)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .setAccountHolder(accountHolder)
        .setOrderNumber(UUID.randomUUID().toString())
        .setOrderItems(arrayListOf(
           OrderItem().apply {
               name = "Item 1"
               articleNumber = "123"
               this.amount = RequestedAmount("5.0", "EUR")
               taxRate = BigDecimal("0.0")
               quantity = 1
           }
        ))
        .setDeviceFingerprint("DeviceIdentToken")
        .build();

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(ratepayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`sdkpay_ecom_color_main`* - color tint for icons, header and submit button
gradient start color

*`sdkpay_ecom_color_main_light`* - header and submit button gradient end
color

*`sdkpay_ecom_color_main_alpha80`* - text input layout title color

*`sdkpay_ecom_color_toolbar_text`* - toolbar text and back arrow tint

*`sdkpay_ecom_color_pay_button_text`* - pay button text color

*`sdkpay_ecom_color_main_background`* - background color for main view

*`sdkpay_ecom_color_error`* - used for all text input layouts to modify
error text color including the edit text line

==== Changing Fonts

To change fonts, override the font path to in string resources with name
`sdkpay_fontPath': e.g. strings.xml

[source,xml]
----
<string name="sdkpay_fontPath">fonts/myFont.otf</string>
----

==== Changing Text Size

To change the text size use dimensional attribute `sdkpay_ecom_text_size`.
This affects all the modules, except `cardField`.

==== Customizing RatePay Payments

[.image]##

*Color Resources*

1 - `sdkpay_ecom_color_main`

2 - `sdkpay_ecom_color_light`

3 - `sdkpay_ecom_color_main_alpha80`

4 - `sdkpay_ecom_color_pay_button_text`

5 - `sdkpay_ecom_color_toolbar_text`

6 - `sdkpay_ecom_color_error`

7 - `sdkpay_ecom_color_main_background`