[#MobilePaymentSDK_Android_MB Way]
---
== *MB Way*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/mbway.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple MB Way Payment

This is a code example for a basic MB Way payment:

[source,kotlin]
----
val mbwayPayment = MbwayPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = "EUR",
        accountHolder = accountHolder,
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(mbwayPayment)
----

[source,java]
----
MbwayPayment mbwayPayment = new MbwayPayment.Builder()
        .setSignature(signature)
        .setRequestId(requestId)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency("EUR")
        .setAccountHolder(new AccountHolder(
            "firstName",
            "lastName",
            "email",
            "phone",
            "gender",
            "dateOfBirth" // "yyyy-MM-dd",
            address
        ))
        .build()

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(mbwayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

In case of providing valid
*`accountHolder.phoneCountryCode`* and *`accountHolder.phone`*
or
*`accountHolder.phone`* which contains both valid country code and phone number
payment flow starts directly, otherwise user will be redirected to screen where phone number needs to be entered.