[#MobilePaymentSDK_Android_Blik]
---
== *Blik*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.DEBIT`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/blik.aar')
    ...
}
----

Blik module contains two payment types:
Blik Level0
Blik Redirect

When adding/removing this feature, perform a full clean build.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple Blik Level0 Payment

This is a code example for a basic Blik Level0 payment:

[source,kotlin]
----
val blikPayment = BlikLevel0Payment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = "PLN",
        accountHolder = accountHolder,
        orderNumber = orderNumber,
        descriptor = descriptor,
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(blikPayment)
----

[source,java]
----
BlikLevel0Payment blikPayment = new BlikLevel0Payment.Builder()
        .setSignature(signature)
        .setRequestId(requestId)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency("PLN")
        .setAccountHolder(new AccountHolder(
            "email"
        ))
        .setOrderNumber("18040037092713285")
        .setDescriptor("DESC180099798888")
        .build()

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(blikPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Simple Blik Redirect Payment

This is a code example for a basic Blik Redirect payment:

[source,kotlin]
----
val blikPayment = BlikRedirectPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = "PLN",
        accountHolder = accountHolder,
        orderNumber = orderNumber,
        descriptor = descriptor,
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(blikPayment)
----

[source,java]
----
BlikRedirectPayment blikPayment = new BlikRedirectPayment.Builder()
        .setSignature(signature)
        .setRequestId(requestId)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency("PLN")
        .setAccountHolder(new AccountHolder(
            "email"
        ))
        .setOrderNumber("18040037092713285")
        .setDescriptor("DESC180099798888")
        .build()

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(blikPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.