[#MobilePaymentSDK_Android_SEPA]
---
== *SEPA Direct Debit*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

*`TransactionType.PENDING_DEBIT`* - represents the request for a debit. If the [Transaction State] is success, then the outcome of the debit is not yet known. A further [Transaction Type] of debit follows, whose [Transaction State] indicates the outcome. If the [Transaction State] of the pending-debit is failed, then the request has not been processed.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/camera.aar')
    implementation files('libs/sepa.aar')
    ...
}
----

To disable the IBAN scanner feature, comment the
'libs/camera.aar' dependency.

When adding/removing this feature, perform a full clean build. If you
intend to use Card Payments module together with the SEPA Direct Debit
module (with enabled IBAN scanner), you must enable it in *both*
modules.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple SEPA Payment

This is a code example for a basic SEPA payment:

[source,kotlin]
----
val sepaPayment = SepaPayment(
        signature = signature,
        requestTimeStamp = timestamp,
        requestID = requestID,
        merchantAccountId = merchantID,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        creditorId = null,
        mandateId = null,
        mandateSignedDate = null,
        merchantName = "JOHN DOE",
        dueDate = null,
        periodic = null,
        B2B = null
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(sepaPayment)
----

[source,java]
----
sepaPayment = new SepaPayment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantID)
        .setRequestId(requestID)
        .setAmount(amount)
        .setTransactionType(transactionType)
        .setCurrency(currency)
        .build();

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(sepaPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Recurring Sepa Payment
---
On a basic level, recurring payments have two phases:

[arabic]
. The initial request, which must include:
* periodic type set to PeriodicType.RECURRING,
* sequence type set to SequenceType.FIRST.
. The follow-up requests, which must include:
* periodic type set to PeriodicType.RECURRING,
* sequence type set to SequenceType.FIRST,
* parentTransactionId value from the initial request.

So in order to create a recurring payment, you need to:

[arabic]
. Send a initial request with the appropriate periodic and sequence flags,
. Save the values of parentTransactionId field generated in this first payment,
. Reference these values in the follow-up request, then send it with appropriate periodic and sequence flags.

This is a code example for a first recurring Sepa payment:
[source,kotlin]
----
// First payment

var parentTransactionId: String? = null

val sepaPayment = SepaPayment(
        signature,
        requestID,
        merchantID,
        transactionType,
        null,
        null
)
sepaPayment.periodic = Periodic().apply {
   periodicType = PeriodicType.RECURRING.value
   sequenceType = SequenceType.FIRST.value
}

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(sepaPayment)

// Handle first result

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)

    if (requestCode == Client.PAYMENT_SDK_REQUEST_CODE) {
        val paymentSdkResponse = data?.getSerializableExtra(Client.EXTRA_PAYMENT_SDK_RESPONSE)
        if (paymentSdkResponse is PaymentResponse) {
            when (paymentSdkResponse.responseCode) {
                ResponseCode.RESULT_OK -> parentTransactionId = paymentSdkResponse.payment?.parentTransactionId
                else -> Toast.makeText(this, "${paymentSdkResponse.responseCode}, ${paymentSdkResponse.errorMessage}", Toast.LENGTH_LONG).show()
            }
        }
    }
}

// Second payment using parentTransactionId

val sepaPayment = SepaPayment(
        signature,
        requestID,
        merchantID,
        transactionType,
        null,
        null
)
sepaPayment.periodic = Periodic().apply {
   periodicType = PeriodicType.RECURRING.value
   sequenceType = SequenceType.RECURRING.value
}
sepaPayment.parentTransactionId = parentTransactionId

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(sepaPayment)
```
----

==== IBAN scanner

If you include 'libs/camera.aar' dependency you can use IBAN scanner feature.
IBAN scanning feature works with use of activity results so for simplification we can use ActivityResultContract.

To start the feature and listen for iban use this code.
[source,kotlin]
----
class ScannerActivityContract(private val intent: Intent) : ActivityResultContract<Unit, CameraResult>() {

    override fun parseResult(resultCode: Int, intent: Intent?): CameraResult = when {
        resultCode != Activity.RESULT_OK -> CameraResult.NoData
        else -> intent?.getParcelableExtra(EXTRA_SCAN_RESULT) ?: CameraResult.NoData
    }

    override fun createIntent(context: Context, input: Unit): Intent {
        return intent
    }

    companion object {
        const val EXTRA_SCAN_RESULT = "EXTRA_SCAN_RESULT"
        const val TAG_LOCALE = "TAG_LOCALE"
    }

}

val iban = registerForActivityResult(
    ScannerActivityContract(
        BaseScannerActivity.createIntent<IbanScannerActivity>(requireContext())
            .apply { putExtra(ScannerActivityContract.TAG_LOCALE, payment?.locale) }
    )
) { result ->
    val iban = result.iban
}
iban.launch()
----
