[#MobilePaymentSDK_Android_Zinia]
---
== *Zinia*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/zinia.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple Zinia Payment

This is a code example for a basic Zinia payment:

[source,kotlin]
----
val ziniaPayment = ZiniaPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = "EUR",
        orderNumber = orderNumber,
        orderItems = orderItems,
        accountHolder = accountHolder,
        shippingAddress = shippingAddress
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(ziniaPayment)
----

[source,java]
----

ZiniaPayment ziniaPayment = new ZiniaPayment.Builder()
            .setSignature(signature)
            .setRequestId(requestId)
            .setMerchantAccountId(merchantID)
            .setTransactionType(transactionType)
            .setAmount(amount)
            .setCurrency("EUR")
            .setAccountHolder(new AccountHolder(
                        "firstName",
                        "lastName",
                        "email",
                        "phone",
                        "gender",
                        "dateOfBirth" // "yyyy-MM-dd",
                        address
                    ))
            .setShippingAddress(new Shipping(
                        "firstName",
                        "lastName",
                        "email",
                        "phone",
                        "gender",
                        "dateOfBirth",
                        new Address(
                            "street1",
                            "street2",
                            "city",
                            "state",
                            "country",
                            "postal-code",
                            "house-number",
                            "house-extension",
                            "unit",
                            "level",
                            "block-no")
                    ))
            .setOrderNumber("18040037092713285")
            .setOrderItems(orderItems)
            .build()


new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(ziniaPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

In case of providing all mandatory fields, payment flow starts directly, otherwise user will be redirected to screen where all mandatory and optional data can be entered.
In case shipping address is not provided, billing address will be used as shipping address.

==== Fields
[arabic]
. Order number (mandatory)
. Order items (mandatory)
. Account holder
* First Name
* Last Name
* Email
* Billing address details
** Street Name
** House Number
** House extension (optional)
** Block number  (optional)
** Level (optional)
** Unit (optional)
** City
** State/region (optional)
** Postal Code
** Country
. Shipping address
* First Name
* Last Name
* Street Name
* House Number
* House extension (optional)
* Block number  (optional)
* Level (optional)
* Unit (optional)
* City
* State/region (optional)
* Postal Code
* Country


=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`sdkpay_ecom_color_main_background`* - background color for main view

*`sdkpay_ecom_color_edittext_text`* - color of text within phone number edittext

*`sdkpay_ecom_color_main_alpha80`* - text input layout title color

*`sdkpay_ecom_color_pay_button_text`* - pay button text color

*`sdkpay_ecom_color_main`* - color tint for icons, header and submit button gradient start color

*`sdkpay_ecom_color_main_light`* - header and submit button gradient end color

*`sdkpay_ecom_color_error`* - used for all text input layouts to modify error text color including the edit text line

==== Changing Fonts

To change fonts, override the font path to in string resources with name
`sdkpay_fontPath': e.g. strings.xml

[source,xml]
----
<string name="sdkpay_fontPath">fonts/myFont.otf</string>
----

==== Changing Text Size

To change the text size use dimensional attribute `sdkpay_ecom_text_size`.
This affects all the modules, except `cardField`.

==== Customizing Zinia Payments

[.image]##

*Color Resources*

1 - `sdkpay_ecom_color_main_background`

2 - `sdkpay_ecom_color_edittext_text`

3 - `sdkpay_ecom_color_main_alpha80`

4 - `sdkpay_ecom_color_pay_button_text`

5 - `sdkpay_ecom_color_main`

6 - `sdkpay_ecom_color_main_light`

7 - `sdkpay_ecom_color_error`
