[#MobilePaymentSDK_Android_MB Way]
---
== *MB Way*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
----
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/mbway.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple MB Way Payment

This is a code example for a basic MB Way payment:

[source,kotlin]
----
val mbwayPayment = MbwayPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = "EUR",
        accountHolder = accountHolder,
)

Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(mbwayPayment)
----

[source,java]
----
MbwayPayment mbwayPayment = new MbwayPayment.Builder()
        .setSignature(signature)
        .setRequestId(requestId)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency("EUR")
        .setAccountHolder(new AccountHolder(
            "firstName",
            "lastName",
            "email",
            "phone",
            "gender",
            "dateOfBirth" // "yyyy-MM-dd",
            address
        ))
        .build()

new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(mbwayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

In case of providing valid
*`accountHolder.phoneCountryCode`* and *`accountHolder.phone`*
or
*`accountHolder.phone`* which contains both valid country code and phone number
payment flow starts directly, otherwise user will be redirected to screen where phone number needs to be entered.

=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`sdkpay_ecom_color_main_background`* - background color for main view

*`sdkpay_ecom_color_edittext_text`* - color of text within phone number edittext

*`sdkpay_ecom_color_main_alpha80`* - text input layout title color

*`sdkpay_ecom_color_pay_button_text`* - pay button text color

*`sdkpay_ecom_color_main`* - color tint for icons, header and submit button gradient start color

*`sdkpay_ecom_color_main_light`* - header and submit button gradient end color

*`sdkpay_ecom_color_error`* - used for all text input layouts to modify error text color including the edit text line

==== Changing Fonts

To change fonts, override the font path to in string resources with name
`sdkpay_fontPath': e.g. strings.xml

[source,xml]
----
<string name="sdkpay_fontPath">fonts/myFont.otf</string>
----

==== Changing Text Size

To change the text size use dimensional attribute `sdkpay_ecom_text_size`.
This affects all the modules, except `cardField`.

==== Customizing MB Way Payments

[.image]##

*Color Resources*

1 - `sdkpay_ecom_color_main_background`

2 - `sdkpay_ecom_color_edittext_text`

3 - `sdkpay_ecom_color_main_alpha80`

4 - `sdkpay_ecom_color_pay_button_text`

5 - `sdkpay_ecom_color_main`

6 - `sdkpay_ecom_color_main_light`

7 - `sdkpay_ecom_color_error`
