[#MobilePaymentSDK_Android_P24]
---
== *P24 (Przelewy24)*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

*`TransactionType.PENDING_DEBIT`* - represents the request for a debit. If the [Transaction State] is success, then the outcome of the debit is not yet known. A further [Transaction Type] of debit follows, whose [Transaction State] indicates the outcome. If the [Transaction State] of the pending-debit is failed, then the request has not been processed.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/p24.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple P24 Payment

This is a code example for a basic P24 payment:

[source,kotlin]
----
val p24Payment = P24Payment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        accountHolder = accountHolder,
        descriptor = null,
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(p24Payment)
----

[source,java]
----
p24Payment = new P24Payment.Builder()
        .setSignature(signature)
        .setMerchantAccountId(merchantId)
        .setRequestId(requestId)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .setAccountHolder(new AccountHolder(
                "Firstname",
                "Lastname",
                "email@mail.com"
        ))
        .build();
 
new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(p24Payment);
----

You can use Builder to create the payment object and set additional
properties afterwards.