[#MobilePaymentSDK_Android_Alipay]
---
== *Alipay Cross Border*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:

*`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.

*`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].

*`TransactionType.PENDING_DEBIT`* - represents the request for a debit. If the [Transaction State] is success, then the outcome of the debit is not yet known. A further [Transaction Type] of debit follows, whose [Transaction State] indicates the outcome. If the [Transaction State] of the pending-debit is failed, then the request has not been processed.

=== Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/alipay.aar')
    ...
}
----

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple Alipay Payment

This is a code example for a basic Alipay payment:

[source,kotlin]
----
val alipayPayment = AlipayPayment(
        signature = signature,
        requestID = requestID,
        merchantAccountId = merchantAccountId,
        transactionType = transactionType,
        amount = amount,
        currency = currency,
        orderNumber = null,
        orderDetail = null,
        locale = null,
        ipAddress = null,
        accountHolder = null,
        businessType = null,
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(alipayPayment)
----

[source,java]
----
alipayPayment = new AlipayPayment.Builder()
        .setSignature(signature)
        .setRequestId(requestID)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .build();
 
new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(alipayPayment);
----

You can use Builder to create the payment object and set additional
properties afterwards.