[#API_CC_3DS2_UseCases_ThirdPartyMPI]
== External 3D Secure Providers

CAUTION: Authentication with external 3D secure providers needs configuration of your merchant account. +
<<ContactUs, Contact merchant support>> to activate this feature.


// pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/third-party-mpi.postman_collection.json" target="_blank" rel="noreferrer noopener" download>Download a Postman collection for this use case option here.</a>] 

The 3D Secure 2 fields can be found in the <<CreditCard_3DS2_Fields, 3D Secure 2 field table>>. +
They are also included in the <<Appendix_Xml, REST API payment XSD>>.

You are a merchant with {payment-provider-name}.

You receive the following 3D Secure 2 values from your external 3D Secure provider (from a 3rd Party MPI rather than {payment-provider-name} MPI) after a successful authentication. You need these values to proceed with the checkout in ``purchase``, ``authorization`` or ``authorization-only`` transactions:

[%autowidth,cols="m,a"]
|===
| three-d/cardholder-authentication-value 
a| *Mandatory.* +
A cryptographic value generated by the issuer. Used for +

* _Visa's_ _Cardholder Authentication Verification Value_ (CAVV) and
* _Mastercard's_ 
** _Accountholder Authentication Value_ (AAV) and 
** _Universal Cardholder Authentication Field_ (UCAF). 

//-
| three-d/eci
| *Mandatory.* +
Indicates the status of the VERes. +
| three-d/ds-transaction-id
| Universally unique transaction identifier assigned by the Directory Server to identify a single transaction. +
*Mandatory* for external 3D Secure servers not provided by {payment-provider-name}. +
Accepted format: see IETF RFC 4122.
| three-d/version
| *Mandatory.* +
Identifies the version of 3D Secure authentication used for the transaction.

//-
| three-d/cardholder-authentication-status
| Status of the 3D Secure check.
|===

//-

When you are ready to ship/deliver:

. *Authorization* (full amount) +
Include the authentication values provided by the external 3D Secure provider.
. *Capture-Authorization* (full amount) +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]

//-