[#API_CC_3DS2_UseCases_OneTimePaymentTransaction]
== One-Time Payment 

One-time payment is one of the most common scenarios. A consumer places an order for a product or service. The merchant fulfills the order in a single shipment and before expiration of the authorization. 

[NOTE]
====
Authentication required: Yes +
Card-on-file flagging required: No 
====
[#API_CC_3DS2_UseCases_OneTimePaymentTransaction_OneStep]
=== Option 1: One-Step Payment with Authentication

Download a Postman collection for this use case option 
pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/one-time-payment-option-one.postman_collection.json" target="_blank" rel="noreferrer noopener" download>here.</a>] 

The 3D Secure 2 fields can be found in the <<CreditCard_3DS2_Fields, 3D Secure 2 Fields>> section. +
They are also included in the <<Appendix_Xml, REST API payment XSD>>.

. *Check-Enrollment* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[] 
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[] 
+
. *Redirect the Consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[] 
+
. *Check-Payer-Response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[] 
+
. *Purchase* +
include::{root}/include/3-d-secure/3-d-secure-2-purchase-transaction.adoc[] 
+
WARNING: Execute this step right after the check-enrollment or check-payer-response, while the consumer is in the session. 

//-

[#API_CC_3DS2_UseCases_OneTimePaymentTransaction_TwoStep]
=== Option 2: Two-Step Payment with Authentication

Download a Postman collection for this use case option 
pass:[<a href="resources/3-d-secure-2/usecase_pm-collection/one-time-payment-option-two.postman_collection.json" target="_blank" rel="noreferrer noopener" download>here.</a>] 

The 3D Secure 2 fields can be found in the <<CreditCard_3DS2_Fields, 3D Secure 2 Fields>> section. +
They are also included in the <<Appendix_Xml, REST API payment XSD>>.

. *Check-Enrollment* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment.adoc[] 
+
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-enrollment-response.adoc[] 
+
. *Redirect the Consumer to the ACS URL* +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-acs-url-redirect.adoc[] 
+
. *Check-Payer-Response* (optional) +
include::{root}/include/3-d-secure/3-d-secure-2-authentication-transactions-check-payer-response.adoc[] 
+
. *Authorization* +
include::{root}/include/3-d-secure/3-d-secure-2-authorization-transaction.adoc[] 
+
WARNING: Execute this step right after the check-enrollment or check-payer-response, while the consumer is in the session. 
+
. *Capture-Authorization* +
include::{root}/include/3-d-secure/3-d-secure-2-capture-authorization-transaction.adoc[]
+
WARNING: Execute this step as soon as the products are ready to ship, within the allowed time limit.

//-
