[#CreditCard_3DS2_Exemption_Adviser]
== Exemption Adviser

You can request for certain types of transactions to be exempted from Strong Customer Authentication (SCA), even though PSD 2 is mandatory. It is up to your bank/acquirer to request these exemptions for you, followed by the approval of the issuer.

Flag a transaction accordingly to indicate if an exemption is desired and Wirecard can request the most applicable SCA exemption.

The card issuing bank can also apply an exemption from SCA regardless of whether or not you or your bank/acquirer requested it. In both cases, if an exemption is applied, the transaction is frictionless.

[WARNING]
====
If the exemption is granted, liability protection is not offered, and the liability remains with you, the merchant (acquirer), in case of chargebacks. 
For details on when the liability protection is granted, go to the <<3DSecureLiabilityShiftRules, liability shift rules overview>>.
====

[#CreditCard_PSD2_SCA_Exemptions]
=== SCA Exemptions

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowValue]] *Low-Value Transactions* 
a| - SCA does NOT apply to transactions below 30 EUR. +
- SCA does NOT apply when the cumulative amount of previous transactions since the last Strong Customer Authentication does not exceed 100 EUR. +
- SCA does NOT apply when five or less consecutive individual online transactions have been made. Remember that in this case, none of those two-to-five payments have been over 30 EUR, and their total does not exceed 100 EUR. +
_The issuer keeps track of the number of transactions and the cumulative transaction amount, reseting the counts each time SCA is performed._

//-

[NOTE]
====
The issuer can apply this exemption even if you and your acquirer did not request for it. In such cases the chargeback liability shifts to the issuer.
====

|===


[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_LowRisk]] *Low-Risk Transactions*
a| - SCA does NOT apply to low-risk transactions. +
  - To determine whether an online transaction is low-risk, acquirers and issuers may perform real-time risk analysis to identify, for example, abnormal spending patterns, known fraud scenarios, and abnormal location of the consumer.

//-

[NOTE]
====
The transaction amount for which a low-risk exemption can be requested varies depending on the acquirer fraud rate. +
The issuer can apply this exemption even if you and your acquirer did not request for it. In such cases the chargeback liability shifts to the issuer.
====

|===

[cols=""]
|===
| [[CreditCard_PSD2_SCA_Exemptions_WhiteList]] *Whitelisting*
a| - SCA does NOT apply to online payments from a consumer to a whitelisted merchant. +
- Consumers can whitelist "trusted beneficiaries", i.e. merchants of their choice, to be included on a list maintained by the consumer's bank. SCA is only required for the first online transaction.

//-

|===


[WARNING]
====
These types of transactions can only be exempted from Strong Customer Authentication if the fraud rates for these transactions are the same as or below the EU reference fraud rate for remote electronic card-based payments.
====

[#CreditCard_PSD2_Fraud]
.EU reference fraud rate for remote electronic card-based payments
[%autowidth]
|===
|Exemption Threshold Value (ETV) |Fraud Rate

| EUR 500 | 0.01 %
| EUR 250 | 0.06 %
| EUR 100 | 0.13 %
|===


[#CreditCard_PSD2_SCA_Exemptions_OutOfScope]
=== Out of Scope for SCA

- Merchant-Initiated Transactions (MIT) +
* SCA must apply when the consumer initiates the first in a series of recurring transactions with the same amount and the same merchant. +
* SCA does NOT apply to all subsequent recurring transactions. +

NOTE: Merchant-initiated transactions must be flagged accordingly. For more information on MITs, go to <<API_CC_3DS2_PaymentFlows, 3D Secure 2 Payment Flows>>. 

- Secure Corporate Transactions +
* SCA does NOT apply to secure B2B payments via dedicated payment processes and protocols which are not available to consumers. +
* If you or your payment service provider identify a transaction as exempted from secure corporate payment, you can send the transaction directly for authorization by using the appropriate flag. +
The issuer remains responsible for exemption validation and should not request SCA for transactions exempted from secure corporate payment. Issuers and their ACS must identify cards of this type based on the product/PAN and communicate to acquirers (via their ACS) that SCA is not required. +
If the issuer identifies a transaction not exempted from secure corporate payment, they must perform a soft decline. +

- Card payments taken via mail (e.g. email, fax, order form) or phone (MOTO transactions)
- "One-leg out transactions", i.e. transactions where either the issuer or the acquirer is not located within the European Economic Area (EEA)
- Transactions using anonymous prepaid cards +

NOTE: These transactions are in scope of AMLD5. As {payment-provider-name} is AMLD5-compliant, different acceptance rules apply.

//-

[#3DSecureLiabilityShift]
=== Liability Shift

3D Secure protects merchants from fraudulent losses by allowing for liability shift after successful cardholder authentication.

Generally, the liability shift rules for 3D Secure 2 are comparable with those for 3D Secure 1: Whenever you successfully request authentication from an issuer, the chargeback liability shifts to the issuer.

There are, however, some exceptions applicable within the European Economic Area (EEA):

- If an exemption is granted after it was requested by you and your acquirer (e.g. you decide to avoid a challenge), liability protection is not offered, and the liability generally remains with you, the merchant (acquirer). 

- If an issuer does not support 3D Secure 2 after SCA requirements have come into effect, there are cases where only attempting to apply 3D Secure 2 will lead to a shift in liability. Nonetheless, the issuer may decline the authorization in case they refuse to take the liability.

//-


[#3DSecureLiabilityShiftRules]
.Liability Shift Rules Overview
[cols=",,,"]
|===
| *Merchant*               
| *Applied Exemption*       
| *Issuer*                                
| *Liability*

.7+| 3D Secure implemented 

| No exemption            
| Does not support 3D Secure            
| Issuer

| <<CreditCard_PSD2_SCA_Exemptions_LowValue, Low-value transactions>>  
| Checks if number of transactions < or =5 and accepts exemption    
| Acquirer

| No exemption
| Applies <<CreditCard_PSD2_SCA_Exemptions_LowValue, low-value transactions>> exemption
| Issuer

| <<CreditCard_PSD2_SCA_Exemptions_LowRisk, Low-risk transactions>>   
| Accepts exemption                     
| Acquirer

| No exemption
| Applies <<CreditCard_PSD2_SCA_Exemptions_LowRisk, low-risk transactions>> exemption
| Issuer

| No exemption
| Performs transaction risk analysis / requests challenge (if preceeding number of low-value transactions =5)
| Issuer

| Merchant-initiated transaction (first)
| Requests challenge
| Issuer
|===


//-