[#CreditCard_PSD2_SCA_Grandfathering]
== Grandfathering

Since 14 September 2019, the PSD 2 Regulatory Technical Standard requires SCA for 3D Secure 2 payment processes. This also applies to recurring payments (see 
https://ec.europa.eu/transparency/regdoc/rep/3/2017/EN/C-2017-7782-F1-EN-MAIN-PART-1.PDF[Article 14 RTS]). From that day on, each first transaction of a recurring merchant-initiated transaction (MIT) must meet the standards of PSD 2.

A special status applies to ongoing recurring MITs whose first transaction was processed before 14 September 2019. Recurring MITs of that kind are "grandfathered".

If {payment-provider-name} is your acquirer, the {payment-gateway} can "grandfather" a recurring MIT if you provide the referencing ``transaction-id`` from the *first* ``authorization`` or ``purchase`` transaction.
 
.Conditions to grandfather a recurring MIT
[%autowidth]
|===

| h| Transaction Date h| <transaction-type> h| <transaction-id> h| <sequence-type> h| <periodic-type> h| <parent-transaction-id>

| First Transaction | Before 14 September 2019 | a) ``authorization`` or +
                                                 b) ``purchase`` | e.g. 12345 | ``first`` | ``recurring`` or +
                                                                                         ``installment`` or +
                                                                                         ``UCOF`` | none
| Recurring Transactions | After 14 September 2019 a| a) ``authorization`` or +
                                                     a) ``referenced-authorization`` or +
                                                     b) ``purchase`` or +
                                                     b) <<CreditCard_TransactionTypes_Purchase_SendingData_ReferencingPurchaseTransactions, ``referenced-purchase``>> |e.g. 56789 | ``recurring`` or +
                                           ``final`` | ``recurring`` or +
                                                       ``installment`` or +
                                                       ``UCOF`` +
                                                       must be the same as in the first transaction. | e.g. 12345 

|===

{payment-provider-name} will then identify the correct Trace ID (Mastercard) or Transaction Identifier (Visa) of this recurring MIT and send it to the issuer. 


//-