[#MobilePaymentSDK_iOS_licence]

---
== *License*
---

=== Payment SDK – MIT License |Open Source
---

Recitals: PagoNxt will offer the payment SDK free of charge, to any person obtaining a copy of this software and associated documentation files under the conditions below. User has to verify the effects of Payment SDK on the implemented environment and will do that at its own risk. Digital downloads are software products. Their contents are protected under copyright and intellectual property law.

Copyright © 2022 PagoNxt Merchant Solutions S.L. and Santander España Merchant Services, Entidad de Pago, S.L.U. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


[#Third_party_licenses]
=== Third-party licenses
---

* [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/LICENSE) - BSD 3-Clause License
* [libextobjc/EXTScope](https://github.com/jspahrsummers/libextobjc/blob/master/LICENSE.md) - MIT Licence
* [AFNetworking](https://github.com/AFNetworking/AFNetworking/blob/master/LICENSE) - MIT Licence
* [Lockbox](https://github.com/granoff/Lockbox/blob/master/LICENSE) - MIT Licence
* [MBProgressHUD](https://github.com/jdg/MBProgressHUD/blob/master/LICENSE) - MIT Licence
* [Mantle](https://github.com/Mantle/Mantle/blob/master/LICENSE.md) - MIT Licence
* [PKeyboardAvoiding](https://github.com/michaeltyson/TPKeyboardAvoiding/blob/master/LICENSE.txt) - zlib License
* [GoogleMLKit/TextRecognition](https://cocoapods.org/pods/GoogleMobileVision) - Apache License 2.0
* [AFNetworking](https://github.com/AFNetworking/AFNetworking/blob/master/LICENSE) - MIT Licence
* [IBAN](https://github.com/stefan-sedlak/IBAN/blob/master/LICENSE) - BSD 2-Clause "Simplified" License
* [Mantle](https://github.com/Mantle/Mantle/blob/master/LICENSE.md) - MIT Licence
* [Mantle](https://github.com/Mantle/Mantle/blob/master/LICENSE.md) - MIT Licence
* [Mantle](https://github.com/Mantle/Mantle/blob/master/LICENSE.md) - MIT Licence
