[#BatchProcessingApi]
== Batch Processing API

[#BatchProcessingApi_Introduction]

In order to process multiple transactions at the same time, Wirecard's _Batch Processing API_ is the ideal and secure solution to implement
quick and easy offline transaction processing.

Batch processing is possible for the following payment methods:

- _SEPA Direct Debit (SEPA DD)_
- _SEPA Credit Transfer (SEPA CT)_
- _Credit Card_

//-


[#BatchProcessingApi_{payment-gateway-abbr}vsSepaConversionService]
=== SEPA Service

Until all merchants have migrated their consumers to SEPA, Wirecard offers a SEPA Conversion Service.

SEPA Transactions included in the {payment-gateway} request
file should not be confused with SEPA Conversion Service (EFT) request
files.

A merchant may send {payment-gateway} request files and EFT
transaction request files to the same SFTP directory. 
{payment-gateway} files should be provided in CSV format, EFT request
files must be submitted in xml. The batch service picks up the appropriate files
according to the file type automatically.

//-
