[#Privacy_Policy]
[discrete]
=== Privacy Policy

_Last updated on 11 December 2019_

. General
Wirecard AG ("Wirecard", "we") offers products and services concerning electronic payment transactions. The aim is to enable companies and consumers to process electronic payments worldwide securely and smoothly. The security and protection of personal data are key aspects of the processing of payments. This is why we attach particular importance to high standards of data protection.
Wirecard operates this website in conformity with the provisions of the GDPR, the BDSG [German Federal Data Protection Act] and all other provisions relevant to data protection law.

. Contact
The controller responsible for your personal data is Wirecard AG, Einsteinring 35, 85609 Aschheim, Germany. 
If you have any questions regarding how we collect, store and use your personal data, or if you wish for a copy of the data stored concerning you, please contact our data protection officer. You can either write to the above address or contact us using this form.  

. What is this website about? 
On this website, we make available to you extensive documentation regarding the Wirecard payment interface. 
The Wirecard Online Documentation offers you technical details, integration examples and additional information relating to the integration and use of Wirecard payment solutions for your e-commerce business.

. Processing of personal data and other data by Wirecard when you visit our website
[arabic]
.. Information automatically collected by you when you visit our website
When you visit this website, we collect the IP address of the terminal device that you use to access our website. We further collect information on the Internet browser used by you, the browser language, the operating system of your terminal device, the areas visited by you on our website, the terms entered in the document search, the circumstance as to whether you are a first-time or recurring visitor to our website, as well as the location of your Internet provider. The aforementioned data are collected in order to evaluate, on the basis of Art. 6 (1), sentence 1, f) GDPR, user behaviour on our website for the purpose of optimising the website. 
.. Passing-on of your personal data 
Your personal data will be used only for the aforementioned purposes and only to the extent necessary for attaining these purposes. In this respect, we pass on collected personal data to the third parties named below.
[arabic]
... Matomo
+
The data collected under subsection 4.1 are passed on to InnoCraft Ltd., 150 Willis St, 6011 Wellington, New Zealand ("Matomo") for the purpose stated therein. In this respect, Matomo processes the data in the cloud operated by Amazon Web Service (AWS) (Amazon Web Services EMEA SARL, 38 Avenue John F. Kennedy, L-1855 Luxembourg) and stores the data in the AWS computer centre in Frankfurt. AWS is certified under ISO 9001, ISO 27001, ISO 27017, ISO 27018 and BSI C5 and participates in the EU-USA Privacy Shield framework agreement. Personal data are processed on the basis of the AWS data protection policy (https://aws.amazon.com/de/privacy/) 
Pseudonymised usage profiles are created and evaluated from these data by Matomo for the same purpose. Cookies may be used for this. Cookies are small text files stored locally in the cache of the website visitor's Internet browser. Among other things, the cookies make it possible to recognise the Internet browser used by you. The information generated by the cookie in the pseudonymous user profile is not used to personally identify the visitor to this website and is not combined with personal data concerning the bearer of the pseudonym. 
If you are not in agreement with the storage and evaluation of these data ensuing from your visit, you may, via the following link, object at any time to their storage and evaluation. In this case, a so-called opt-out cookie will be installed onto your browser, the consequence being that we shall not pass on any data to Matomo. Please note that complete deletion of your cookies will result in the opt-out cookie also being deleted and in you possibly having to re-activate the opt-out cookie.
+
++++
<iframe style="border: 0; height: 200px; width: 600px;"
src="https://wirecard.matomo.cloud/index.php?module=CoreAdminHome&action=optOut&backgroundColor=&fontColor=&fontSize=&fontFamily=sans-serif"></iframe>
++++
+
... Inter-group companies of the Wirecard Group
Your personal data will be passed on to affiliates of Wirecard AG within the meaning of Sections 15 et seqq. AktG [Public Limited Companies Act], insofar as this is necessary for attaining the aforementioned purpose. 
... Governmental institutions and authorities
Transfers of personal data to governmental institutions and authorities take place only within the scope of mandatory national legal provisions, or if disclosure is necessary for the purposes of legal action or criminal prosecution in the event of misuse or fraud. The legal basis for such passing-on of data is Art. 6 (1), sentence 1, c) GDPR. 
. International data transfer
Your personal data will not be processed outside of the European Union.
. Data storage
Notwithstanding any statutory retention duties, in particular under fiscal or accounting law, we store your personal data as long as necessary for fulfilling the purpose for which the data were collected. 
. Data security
We have taken appropriate organisational, technical and administrative measures to protect the personal data against being lost, falsified or passed on to unauthorised third parties. Wirecard uses firewalls to prevent unauthorised access to servers; the servers are located in a secure place in Germany that only authorised employees have access to. All employees and all persons involved in data processing are obliged to comply with all provisions of data protection law and to handle personal data with confidentiality.
. Your data protection rights
Under the GDPR, users have certain rights as data subjects, in particular the right of access to, and rectification, updating or erasure of, their personal data stored by us. 
If you wish to exercise any of these rights, you can do so at any time by contacting us using this form.
You can object to the processing of your personal data, ask us to restrict the processing of your personal data or obtain portability of your personal data. Here too, you may exercise these rights by contacting us using this form.
Likewise, you may revoke your consent at any time if we have collected and processed your personal data with your consent. Revocation of your consent will not affect the lawfulness of any processing undertaken by us prior to your revocation or affect the processing of your personal data that takes place in reliance upon lawful grounds for processing other than consent.
You have the right to lodge with a data protection authority a complaint concerning the collection and use of your personal data. For further information, please contact us using this form.

//-
