[#CreditCard_PaymentFeatures]
== Payment Features

[#CreditCard_PaymentFeatures_Tokenization]
=== Tokenization

[#CreditCard_PaymentFeatures_Tokenization_Introduction]
==== Introduction

Tokenization defines a process through which sensitive data, such as
credit card number, is replaced with a surrogate value known as a
"token". This token serves as a reference or surrogate value for the original credit card data.

Tokenization enables the merchant to use credit card data based on PCI
DSS regulations, during a payment process.

It is a service provided by _{payment-provider-name}_ for its customers. The token,
generated by _{payment-provider-name}_, reduces the merchant's PCI DSS Scope. That means,
merchants do not have to store sensitive primary account numbers.


There are two options of using tokenization:

.  *Sending a Credit Card Transaction with Credit Card Data*: +
{payment-gateway} takes the credit card data
and encrypts the data. These data are stored in a secured encrypted area
inside _{data-warehouse}_ and are for use only in the encrypted
state and secured environment. +
*In other words:* Every card number that accompanies a transaction in
{payment-gateway} is subsequently tokenized.
Regardless of the outcome of the transaction, any subsequent transaction
with these credit card data uses its assigned token instead of the clear
card account values. This means the merchant system never needs to store
the sensitive card information, helping to reduce PCI DSS compliance
issues.

. *Sending an Explicit Request with the Transaction Type _Tokenize_ or _Detokenize_*. +
A transaction with this transaction type encrypts or
decrypts credit card data for later reuse. The sender only gets back a
_token-ID_. This _token-ID_ can be reused many times as unique
identifier for this specific credit card without sending or storing
credit card data on shop side.
//-

What is the difference between these two options?

[cols="1,2"]
|===
|Sending a Credit Card Transaction with Credit Card Data |Sending an Explicit Request with the Transaction Type _tokenize_ or _detokenize_

|always initiates a payment process *and* encrypts credit card data |encrypts credit card data only
|  |*does not* initiate a payment process
|===

[#CreditCard_PaymentFeatures_Tokenization_TokenID]
==== The _token-id_

The merchant sends an initial request to _{payment-gateway}_.
This could be an _authorization_, for example. This request contains all
data concerning the goods, shipping etc, as well as the consumer's
credit card data. +

After the request of an _authorization_ transaction was processed
successfully, the response will not contain the information of the
Credit Card <data> tag. The <data> tag will be replaced with
a _token-id_ in the <card-token> tag. As soon as
the _token-id_ is created, the _token-id_ represents this
special credit card. +

With that _token-id_ any recurring or other follow up transaction
for this special credit card can be processed. As there is no additional
encryption required, the use of the _token-id_ reduces interaction
and accelerates the credit card payment process. Especially from PCI DSS
perspective, it is less critical. +

e.g. A _capture-authorization_ as follow up transaction in the workflow
does not need the <data> tag of the Credit Card but only the
_token-id_.

_When using credit card, {payment-gateway}_ offers two different
options to reference transactions. It depends on the merchant's
individual business needs and business processes, which type of
referencing should be used.

Look at the following table to understand the pros and cons of
referencing with a token or with the
<<GeneralPlatformFeatures_ReferencingTransaction, parent-transaction-id>>.

[cols="1,2,3"]
|===
| |_parent-transaction-id_ |_token-id_

.4+|Pro |Can be used for all alternative payment methods and _credit card_. |
       |Recurring transactions can always reference to a FIRST transaction. | Once created, the token can be reused as often as needed.
       |Referencing is possible to a previous transaction during the life cycle of a payment process. |Credit card check is only performed once (with the first transaction). Makes the payment process faster.
       |Reference is possible even on older transactions. |Reference is valid ad long as the _credit card_ is valid.
.2+|Con |Referencing only within one life cycle of a payment process. |Can only be used with _credit card_.
       |When used with _credit card_ all card checks have to be performed with every new transaction step. |If card has expired, new token will be needed, even if the card number remains the same.
|===


NOTE: When processing _credit card_ transactions, the merchant must be PCI DSS
compliant.

If the merchant only hands through a payment process (using a token) and
does not store card holder data, it reduces the merchant's applicable
controls required for PCI DSS validation.

If the merchant wants to store card holder data (using
``parent-transaction-id``), it increases the merchant's applicable controls
required for PCI DSS validation.

The following table describes, which data can be stored and which data
must not be stored to be PCI DSS compliant.

[cols="1,2,3,4,5"]
[%autowidth]
|===
2+| |Data Element |Storage permitted? |Data needs to be unreadable (in line with PCI DSS requirements)?
.7+|Account Data .4+|Card holder data |Primary Account Number (PAN) |YES |YES
                                      |Card holder name |YES |NO
                                      |Service code |YES |NO
                                      |Expiration date |YES |NO
                    .3+|Sensitive Authentication Data |Full track data |NO |Doesn't apply
                                                      |CAV2/CVC2/CVV2/CID |NO |Doesn't apply
                                                      |PIN/PIN Block |NO |Doesn't apply
|===


[#CreditCard_PaymentFeatures_Tokenization_TokenID_Referencing]
*Referencing by _token-id_*

Referencing based on a token can be performed by using the Field
``<token-id>``.

With that feature it is possible to refer a NEW transaction to an
already submitted initial transaction. In the initial transaction the
cluster of the ``<card>`` tag will be summarized in a _token-id_.
This _token-id_ will be used in any subsequent transaction, which is
based on this initial transaction. The _token-id_ can be seen as a
black box which guarantees a correct correlation of subsequent
transactions without transmitting the complete card data repeatedly.

[cols="1,2,3, 4, 5"]
[%autowidth]
|===
.2+h|Transaction Sequence .2+h|Transaction Type 2+h|Token-ID .2+h|<card-token>
                                                h|Token Definition h|Value

|Initial transaction (Request) |authorization |the ``<card>``-section and all its fields +
e.g.: ``<account-number>``, ``<expiration-month>``, etc +
obtains the substitute _token-id_ value
|1234567890987654 |empty
|Response on initial transaction |authorization 2+|uses _token-id_ value generated from ``<card>`` data given in the initial transaction |1234567890987654
|Any subsequent transaction of this initial transaction |purchase 2+|uses _token-id_ value generated from ``<card>`` data given in the initial transaction |1234567890987654
|===

See the
<<CreditCard_Samples_PaymentProcessUsingToken,samples for an overview of a payment process>>
consisting of the transaction
types _authorization_ and _purchase_ using a token.


[#CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard]
==== Tokenize a Credit Card

The transaction type _tokenize_ converts credit card information into a
token that can be used in subsequent payment transactions, instead of
the actual credit card information.

[#CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Workflow]
*Workflow*

image::images/diagrams/cc-workflow-tokenization.svg[Create_TokenID_Workflow]


[#CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields]
*Fields*

The following fields must be sent either in the request or the response
(M = Mandatory, O = Optional). For details of the affected fields see
<<CC_Fields, the field table>>.

[col="1,2,3"]
|===
|Field |Request |Response

3+a|
[[CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields_payment]]
[discrete]
==== payment

|merchant-account-id |M |M
|transaction-id |M |
|request-id |M |M
|transaction-type |M |
|ip-address |O |

3+a|
[[CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields_statuses]]
[discrete]
==== statuses

|statuses.status | |M
|status@code | |M
|status@description | |M
|status@severity | |M

3+a|
[[CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields_accountHolder]]
[discrete]
==== account-holder

|account-holder.first-name |O |M
|account-holder.last-name |O |M
|account-holder.email |O |M
|account-holder.gender |O |M
|account-holder.date-of-birth |O |M
|account-holder.phone |O |M

3+a|
[[CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields_card]]
[discrete]
==== card

|card.account-number |M |
|card.expiration-month |M |
|card.expiration-year |O |
|card.card-type |M |

3+a|
[[CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Fields_cardToken]]
[discrete]
==== card-token

|card-token.token-id | |M
|card-token.token-ext-id | |O
|card-token.masked-account-number |O |
|===

[#CreditCard_PaymentFeatures_Tokenization_TokenizeCreditCard_Samples]
*Samples*

For transaction process details see the
<<CreditCard_Samples_Tokenization, _Tokenize_ samples>>.


[#CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard]
==== Detokenize a Credit Card

The transaction type _detokenize_ is the inverse of the transaction type
_tokenize._ With the transaction type _detokenize_ a _token-id_ is
provided to retrieve the original credit card information.

[#CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields]
*Fields*

The following fields must be sent either in the request or the response
(M = Mandatory, O = Optional). For details of the affected fields see
<<CC_Fields, the field table>>.

[col="1,2,3"]
|===
|Field |Request |Response

3+a|
[[CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields_payment]]
[discrete]
==== payment

|merchant-account-id |M |M
|transaction-id | |M
|request-id |M |M
|transaction-type | |M
|ip-address | |O

3+a|
[[CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields_statuses]]
[discrete]
==== statuses

|statuses.status | |M
|status@code | |M
|status@description | |M
|status@severity | |M

3+a|
[[CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields_accountHolder]]
[discrete]
==== account-holder

|account-holder.first-name |M |O
|account-holder.last-name |M |O
|account-holder.email |M |O
|account-holder.gender |M |O
|account-holder.date-of-birth |M |O
|account-holder.phone |M |O

3+a|
[[CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields_card]]
[discrete]
==== card

|card.account-number | |M
|card.expiration-month | |M
|card.expiration-year | |O
|card.card-type | |M

3+a|
[[CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Fields_cardToken]]
[discrete]
==== card-token

|card-token.token-id |M |M
|card-token.token-ext-id |O |O
|card-token.masked-account-number | |O
|===

[#CreditCard_PaymentFeatures_Tokenization_DetokenizeCreditCard_Samples]
*Samples*

For transaction process details see the
<<CreditCard_Samples_Detokenization, _detokenize_ samples>>.

NOTE: The transaction type _detokenize_ *is not included in default configuration.* +
For further information please contact: {e-mail-support}


[#CreditCard_PaymentFeatures_DynamicDescriptor]
=== Dynamic Descriptor

With the _Dynamic Descriptor_, merchants can itemize sales more clearly
to the benefit of their customers, back office and consumer care
management.

As merchants can add sales-specific information to electronic settlement
requests, consumers have a better understanding of what they purchased.
This increases their level of satisfaction and reduces the number of
chargebacks. Known as a dynamic descriptor, the details can be included
in any settlement transaction, be it e-commerce, POS or MOTO.

[#CreditCard_PaymentFeatures_DynamicDescriptor_DataStructure]
==== Data and Structure

_Merchant Name_ and _Merchant Location_ are usually displayed on the
cardholder's bank statement. These fields or parts of them are used for
presenting the dynamic data on the cardholder's statement.

Apart from such static data, the merchant can add transaction
information to better reference their sales. For example, the merchant
may use invoice number, booking ID or transaction ID. This data is
typically passed along to the merchant. As this field has a fixed
length, the longer the merchant name is, the smaller the number of
digits allocated to dynamic information will be.

[#CreditCard_PaymentFeatures_DynamicDescriptor_DataStructure_DigitsAllocation]
*Digits Allocation*

[cols="1,2,3"]
[%autowidth]
|===
|Card Brand |Field |Digits
.2+|VISA |Name |25
         |Location |13
.2+|Master Card |Name |22
                |Location |13
.2+|JCB |Name |25
        |Location |13
|===

NOTE: Merchants are advised to consider all these parameters before setting a
dynamic descriptor, because any text exceeding the permissible length is
cut off and discarded.

Please be aware that industry-specific restrictions apply by card
schemes.

Please also note that it is up to the issuer to decide which data
provided in the dynamic descriptor is printed on the cardholder's
statement. {payment-provider-name} can thus not guarantee that the dynamic descriptor
data submitted to the issuers via the scheme networks is fully printed
on the cardholder's statement.

{payment-provider-name} receives the transaction data from the {payment-gateway}, looks up the merchant address, consolidates static
address details and dynamic sales data (including _Merchant Name_ and
_Merchant Location_) and routes the information along with the
settlement request to the issuer. To what level the routed details will
later appear on the customer's card statement may vary from issuer to
issuer.


[#CreditCard_PaymentFeatures_DynamicDescriptor_HowItWorks]
==== How It Works

When a merchant sends a transaction request with a dynamic descriptor,
the data provided in the reserved transaction field tag expands the
address information registered in the card acquirer's MID database.

NOTE: The dynamic descriptor is created for settlement transaction types such
as ``purchase``, ``capture`` or ``credit``. ``authorization`` is not supported.

[#CreditCard_PaymentFeatures_DynamicDescriptor_HowItWorks_Workflow]
*Workflow*

image::images/diagrams/cc_dynamic-descriptor.bmp[CreditCard DynamicDescriptor Workflow]


. The consumer shops at the merchant's site and enters his card
details at checkout.
. The merchant system records the data and posts an XML request
with the default identifiers including the descriptor text (entered in
one of the <Transaction-ID>, <Order Number>, <Request ID> or
<Descriptor> tag) to the {payment-gateway}.
. {payment-gateway} processes the request and forwards
the transaction details to the acquirer
(e.g. {payment-provider-name} ).
. The acquirer acquires the card and sales details, reads the
related identifier values, looks up the merchant's name and business
details in the MID database and complements the merchant data with the
data sent in one of the transaction identifier tag fields.
. The aquirer routes the settlement request including the
dynamic text to the issuer.
. The issuer processes the request, debits the consumer's
account and adds a new debit item with the dynamic descriptor to the
credit card statement.

//-

[#CreditCard_PaymentFeatures_PaymentFacilitator]
=== Payment Facilitator

The _Payment Facilitator_ model allows a Payment Service Provider with a
_Payment Facilitator_ license to aggregate credit card payments, collect
funds resulting from credit card traffic and settle sub merchants
directly.

Requests in _Payment Facilitator_ traffic require additional sub
merchant information in the
<<CC_Fields_xmlelements_request_submerchantinfo, ``sub-merchant-info``>>
tag of each first request in the transaction flow (e.g.
``check-enrollment``, ``authorization-only``, ``authorization`` or
``purchase``).

The sub merchant information is mandatory for MasterCard, Visa, UPI and JCB traffic.

NOTE: For each transaction flow the first request must contain ``sub-merchant-info``. For the following steps ``sub-merchant-info`` is not
mandatory. We recommend to send ``sub-merchant-info`` in every step. This avoids complexity in implementation.

For details contact <<ContactUs, Merchant Support>>.


[#CreditCard_PaymentFeatures_PaymentFacilitator_HowItWorks]
==== How It Works

image::images/diagrams/cc_payment_facilitator.svg[CreditCard_PaymentFacilitator_Workflow]


See the
<<CreditCard_Samples_PaymentFacilitatorTransactions, corresponding samples for details>>.


[#CreditCard_PaymentFeatures_RecurringTransaction]
=== Recurring Transaction

To submit a
<<GeneralPlatformFeatures_Transactions_Recurring, recurring transaction>>
the merchant must submit a request with the transaction
type ``authorization-only``, ``authorization`` or ``purchase`` including
the
<<GeneralPlatformFeatures_Transactions_Recurring_Periodic, PERIODIC TYPE>>
element and a
<<GeneralPlatformFeatures_Transactions_Recurring_Sequence, SEQUENCE TYPE>>.

[#CreditCard_PaymentFeatures_RecurringTransaction_PeriodicTypes]
==== Credit Card specific _Periodic Types_

Aside from the standard _Periodic Types, Credit Card_ can also be used
with the _Periodic Types_ ``ucof`` and ``ci``.

[#CreditCard_PaymentFeatures_RecurringTransaction_PeriodicTypes_ucof]
*_ucof_*

_The Unscheduled Credential on File (ucof)_ allows the merchant to
reference a regularly based transaction (like an unlimited periodic
payment or an installment payment) to an already successfully submitted
transaction. ``ucof`` is a transaction using a stored credential for a
fixed or variable amount that does not occur on a scheduled or regularly
occurring transaction date, where the cardholder has provided consent
for the merchant to initiate one or more future transactions. An example
of such transaction is an account auto-top up transaction.

[#CreditCard_PaymentFeatures_RecurringTransaction_PeriodicTypes_ci]
*_ci_*

The periodic type ``ci`` (Consumer Initiated) allows the merchant to
identify that the cardholder himself initiated the transaction and
whether this is an initial (first) or subsequent (recurring) one. As
soon as this is subsequent merchant initiated transaction (e.g. the
cardholder used an account on merchant side ) and the corresponding
information is sent to _{payment-gateway},_ _CVV_ could be omitted
within the transaction and Visa will still approve it. So this will lead
to higher approve rate in the future.

[#CreditCard_PaymentFeatures_RecurringTransaction_Restrictions]
==== Restrictions

Read, which
<<GeneralPlatformFeatures_Transactions_Recurring_Restrictions, restrictions>>
have to be met to use a recurring transaction.

[#CreditCard_PaymentFeatures_RecurringTransaction_Samples]
==== Samples

See
<<CreditCard_Samples, request/response samples>> for _Recurring Transaction._

[#CreditCard_PaymentFeatures_RecurringTransaction_PossibleScenarios]
==== Possible Scenarios

[#CreditCard_PaymentFeatures_RecurringTransaction_PossibleScenarios_ShoppingOnline]
*Shopping Online/Via an App*

_Establish Stored Credential/First Transaction_

. Cardholder consent is obtained: ``merchant-tokenization-flag`` set
to ``true``
. Cardholder provides the Credit Card data including _CVV/CVC2_ code
(required): ``periodic/periodic-type = 'ci'`` included in the transaction
and ``periodic/sequence-type = 'first'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: Establishment of Stored Credential/First Transaction
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosShoppingOnline_CptCCdiCc.xml[]
----

_Subsequent Cardholder Initiated Purchase_

. Cardholder consent is obtained: ``merchant-tokenization-flag`` set
to ``true``
. Cardholder data is saved within a cardholder's account (_CVV_ is not
required)
. Cardholder uses the account to make a
purchase: ``periodic/periodic-type = 'ci'`` included in the transaction
and ``periodic/sequence-type = 'recurring'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: Subsequent Cardholder initiated purchase
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosShoppingOnline_CardholderUsesTheAccountToMakeA.xml[]
----

_Guest Account/Single Transaction_

. Since Cardholder doesn't create a account, Cardholder data is not
being saved: the default value for ``merchant-tokenization-flag`` is
``false``
. Cardholder provides the Credit Card data including _CVV/CVC2_ code
(required)
. Merchant sends the transaction to {payment-gateway}

//-

.Example: Guest account/single transaction
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosShoppingOnline_CptCCdiCc_3.xml[]
----

[#CreditCard_PaymentFeatures_RecurringTransaction_PossibleScenarios_RecurringInstallmentTransaction]
*Recurring \(R) or Installment (I) Transaction*

_First Recurring or Installment_

. Cardholder consent is obtained: ``merchant-tokenization-flag`` set
to ``true``
. Cardholder would like to initiate Recurring or Installment payments
. Cardholder provides the Credit Card data including _CVV/CVC2_
code: ``periodic/periodic-type = 'installment'``/``'recurring'`` included in
the transaction and ``periodic/sequence-type = 'first'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: First Recurring or Installment
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosRecurringInstallmentTransaction_CptCCdiC.xml[]
----

[#CreditCard_PaymentFeatures_RecurringTransaction_PossibleScenarios_SubsequentRecurringInstallment]
*Subsequent Recurring or Installment*

_Merchant Initiated Transaction_

. Merchant initiates a subsequent Recurring or Installment
payment: ``periodic/periodic-type = 'installment'``/``'recurring'`` included
in the transaction and ``periodic/sequence-type = 'recurring'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: Merchant initiated transaction
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransaction_SubsequentRecurringOrInstallment.xml[]
----

[#CreditCard_PaymentFeatures_RecurringTransaction_PossibleScenarios_ucof]
*ucof*

_Example_: auto-top up for transit or mobile - date is irregular, i.e.
not known as usage driven

. Cardholder consent is obtained: ``merchant-tokenization-flag`` set
to ``true``
. Cardholder would like to initiate _ucof_ payments
. Cardholder provides the Credit Card data including _CVV/CVC2_
code: ``periodic/periodic-type = 'ucof'`` included in the transaction
and ``periodic/sequence-type = 'first'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: First UCOF (sequence-type = 'first')
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosUcof_CptCCdiC.xml[]
----

_Merchant Initiated Transaction_

. Merchant initiates a subsequent UCOF
payment: ``periodic/periodic-type = 'ucof'``  included in the transaction
and ``periodic/sequence-type = 'recurring'``
. Merchant sends the transaction to {payment-gateway}

//-

.Example: Subsequent UCOF (sequence-type = 'recurring')
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/CreditCardPaymentFeaturesRecurringTransactionPossibleScenariosUcof_MerchantInitiatesASubsequent_UCOF.xml[]
----

[#CreditCard_PaymentFeatures_RecurringTransactions_NonReferencedCapture]
==== Non-Referenced Capture

In an offline transaction process it is possible to have a
non-referenced capture authorization. The {payment-gateway} can
support such a type of transaction when using a special
``capture-authorization`` _Credit Card_ transaction.

A transaction is considered non-referenced capture when it meets all
the  following four conditions in the payment XML request:

. The transaction type is ``capture-authorization``
. ``payment-method`` is _Credit Card_
. ``parent-transaction-id`` is empty (no tag present)
. ``authorization-code`` is present (can have empty value)

//-

If all conditions are met, then the transaction is sent to {payment-gateway}.

The most exceptional fact in this process is, that it is missing the
_Parent-Transaction-ID_. By default ``capture-authorization`` takes most
of its properties from the parent transaction.

Even though no parent transaction is available, captures which have not
been referenced by {payment-gateway} can be processed. Cases
like this will be handled a non-referenced ``capture-authorization``
transaction type. In that case all fields must be supplied with the
_capture-authorization_ request.
