[#AppendixK]
== Test Data and Credentials

NOTE: Test Credentials are now integrated into the corresponding payment method documentation.
Please follow the link below to find the credentials you are looking
for.

.Credit Card

- *Credit Card:* see
<<CreditCard_TestCredentials, Credit Card Test Credentials>>

[NOTE]
====
Click <<API_CC_TestCards, Test Credit Cards>> to find a list of card numbers to
test 3D Secure and Non-3D Secure cards of different brands.
====

.Alternative Payment Methods

- *Alipay Cross-border:* see
<<AlipayCrossBorder_TestCredentials, Alipay Cross-border Test Credentials>>
- *Alipay Domestic:* see
<<AlipayDomestic_TestCredentials, Alipay Domestic Test Credentials>>
- *Alipay QR Pay:* see
<<AlipayQRPay_TestCredentials, Alipay QR Pay Test Credentials>>
- *Bancontact:* see
<<Bancontact_TestCredentials, Bancontact Test Credentials>>
- *Boleto:* see
<<Boleto_TestCredentials, Boleto Test Credentials>>
- *Carrier Billing:* see
<<CarrierBilling_TestCredentials, Carrier Billing Test Credentials>>
- *CIMB Clicks:* see
<<CIMBClicks_TestCredentials, CIMB Clicks Test Credentials>>
- *eps-Überweisung:* see
<<eps_TestCredentials, eps-Überweisung Test Credentials>>
- *giropay:* see
<<giropay_TestCredentials, giropay Test Credentials>>
- *iDEAL:* see
<<iDEAL_TestCredentials, iDEAL Test Credentials>>
- *Klarna Guaranteed Invoice and Installments:* see
<<Klarna_TestCredentials, Klarna Test Credentials>>
- *Klarna Payments (Pay now, Pay later, Financing):* see
<<KlarnaV2_TestCredentials, Klarna Pay now, Pay later, Financing Test Credentials>>
- *Masterpass:* see
<<API_Masterpass_TestCredentials, Masterpass Test Credentials>>
- *Maybank2u:* see
<<Maybank2u_TestCredentials, Maybank2u Test Credentials>>
- *MOLPay:* see
<<MOLPay_TestCredentials, MOLPay Test Credentials>>
- *Moneta.ru:* see
<<monetaRu_TestCredentials, moneta.ru Test Credentials>>
- *Pay by Bank app:* see
<<PaybyBankapp_TestCredentials, Pay by Bank app Test Credentials>>
- *Paydirekt:* see
<<paydirekt_TestCredentials, paydirekt Test Credentials>>
- *Payment On Invoice/Payment In Advance:* see
<<POIPIA_TestCredentials, Payment On Invoice/Payment In Advance Test Credentials>>
- *payolution:* see
<<payolution_TestCredentials, payolution Test Credentials>>
- *PayPal:* see
<<PayPal_TestCredentials, PayPal Test Credentials>>
- *Paysafecard:* see
<<paysafecard_TestCredentials, paysafecard Test Credentials>>
- *POLi:* see
<<POLi_TestCredentials, POLi Test Credentials>>
- *Przelewy24 (P24):* see
<<Przelewy24_TestCredentials, P24 Test Credentials>>
- *SEPA:* see
<<SEPADirectDebit_TestCredentials, SEPA Direct Debit Test Credentials>> and
<<SEPACreditTransfer_TestCredentials, SEPA Credit Transfer Test Credentials>>
- *Skrill Digital Wallet:* see
<<SkrillDigitalWallet_TestCredentials, Skrill Digital Wallet Test Credentials>>
- *Sofort.:* see
<<Sofort_TestCredentials, Sofort. Test Credentials>>
- *Trustly:* see
<<Trustly_TestCredentials, Trustly Test Credentials>>
- *TrustPay:* see
<<TrustPay_TestCredentials, TrustPay Test Credentials>>
- *VISA Checkout:* see
<<VISACheckout_TestCredentials, VISA Checkout Test Credentials>>
- *WeChat QRPay:* see
<<WeChatQRPay_TestCredentials, WeChat QRPay Test Credentials>>
- *{payment-provider-name} Payment Guaranteed Direct Debit:* see
<<API_PaymentDirectDebit_TestCredentials, {payment-provider-name} Payment Guaranteed Direct Debit Test Credentials>>
- *{payment-provider-name} Payment in Installments:* see
<<API_PaymentInstallment_TestCredentials, {payment-provider-name} Payment in Installments Test Credentials>>
- *{payment-provider-name} Payment on Invoice:* see
<<API_PaymentInvoice_TestCredentials, {payment-provider-name} Payment on Invoice Test Credentials>>
- *{payment-provider-name} Voucher:* see
<<WirecardVoucher_TestCredentials, {payment-provider-name} Voucher Test Credentials>>

//-
