[#AppendixI]
[#AppendixI_FAQ]
== FAQ

[#AppendixI_FAQ_RestApiIntegration]
[discrete]
=== REST API Integration

[#AppendixI_FAQ_Error_NoProviderAccount]
.I receive the following response when trying to process a transaction: +
_<status code="400.1048" description="This Merchant Account does not have a Provider Account associated with it. Please contact technical support." severity="error"/>_ +

You are passing a payment method, card type, or currency that is not
properly configured on your merchant account. Please contact your PSP to
double-check your merchant account setup.

'''''

[#AppendixI_FAQ_Error_SameRequestId]
.I keep receiving duplicate Request Id errors: +
_<status code="400.1018" description="The same Request Id for the Merchant Account is being tried a second time. Please use another Request Id." severity="error"/>_ +

The ``request-id`` must be unique for every transaction. If the
problem persists, please contact technical support as it can also be an
indication of a technical error.

'''''

[#AppendixI_FAQ_HtmlInsteadOfXmlResponse]
.When submitting and/or querying transactions, I receive the following HTML response, but would like it to be in XML format instead:

[source,html]
----
include::{root}/samples/html/AppendixI_FAQ_HtmlInsteadOfXmlResponse_WsaqtIagtHrbbwlitbif.html[]
----

Please ensure that the HTTP Content-Type header to is set to "application/xml" in your request.

``Content-Type: application/xml``

'''''

[#AppendixI_FAQ_Credentials]
.Where do I put my username and password when sending a transaction?
Authentication is done via Basic HTTP authentication. For more information, go to 
https://en.wikipedia.org/wiki/Basic_access_authentication#Protocol.

'''''

[#AppendixI_FAQ_EmptyResponse]
.My REST transaction query produces an empty response.
Please double-check the ``merchant-account-id`` you are using. In addition,
you must supply a valid ``request-id`` that references a submitted
transaction.

'''''

[#AppendixI_FAQ_SubmitRecurringAuthorizationRequest]
.How can I submit a successful recurring authorization request?
There are two ways to perform recurring transactions:

. By using the transaction type referenced-authorization or referenced-purchase for
subsequent/recurring transactions.
+
.Request

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/AppendixI_FAQ_SubmitRecurringAuthorizationRequest_Request.xml[]
----
+
.Response

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_referenced-authorization_response_.xml[]
----
+
. By leveraging the token information from the initial
transaction response to do subsequent/recurring transactions.
+
.Request

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/AppendixI_FAQ_SubmitRecurringAuthorizationRequest_Request_9.xml[]
----
+
.Response

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/AppendixI_FAQ_SubmitRecurringAuthorizationRequest_Response_10.xml[]
----

//-
