[#MobilePaymentSDK_Android_P24]
---
== *P24*
---
=== Supported https://docs.getneteurope.com/AppendixB.html[Transaction Types]
---
This payment method supports the following
https://docs.getneteurope.com/AppendixB.html[transaction
types]:
* *`TransactionType.AUTHORIZATION`* - places the account holder’s funds on hold, pending future capture, re-authorization or void transaction.
* *`TransactionType.DEBIT`* - Moves funds from the [Account Holder] to the [Merchant].
* *`TransactionType.PENDING_DEBIT`* - represents the request for a debit. If the [Transaction State] is success, then the outcome of the debit is not yet known. A further [Transaction Type] of debit follows, whose [Transaction State] indicates the outcome. If the [Transaction State] of the pending-debit is failed, then the request has not been processed.

== P24

=== Supported Transaction Types

## Module Dependency Edit your
`build.gradle` file accordingly:

[source,java]
---- 
dependencies {
    ...
    implementation files('libs/core.aar')
    implementation files('libs/p24.aar')
    ...
}
----

To disable the IBAN scanner feature, uncomment the `exclude module`
line.

When adding/removing this feature, perform a full clean build. If you
intend to use Card Payments module together with the WIRETRANSFER Direct Debit
module (with IBAN scanner), you must enable/disable it in *both*
modules.

=== Signature

Application shall get signature from server where signature shall be
computed.

=== Simple P24 Payment

This is a code example for a basic P24 payment:

[source,kotlin]
----
val p24Payment = P24Payment(
        signature = signature
        requestID = requestID
        merchantAccountId = merchantAccountId
        transactionType = transactionType
        amount = amount
        currency = currency
        accountHolder = accountHolder
        ipAddress = null
        orderNumber = null
        orderDetail = null
        descriptor = null
        notifications = null
        customFields = null
)
 
Client(context = this, url = "https://api-test.getneteurope.com", requestTimeout).startPayment(p24Payment)
----

[source,java]
----
p24Payment = new P24Payment.Builder()
        .setSignature(signature)
        .setRequestId(requestID)
        .setMerchantAccountId(merchantID)
        .setTransactionType(transactionType)
        .setAmount(amount)
        .setCurrency(currency)
        .setMerchantName("JOHN DOE")
        .build();
 
new Client(context, "https://api-test.getneteurope.com", requestTimeout).startPayment(p24Payment);
----

You can use Builder to create the payment object and set additional
properties afterwards.

=== Customizing Visuals

To change colors within the SDK, override the default color values in
the `.xml` file.

==== Color Resources

Changing any of these will affect every module used in the SDK:

*`wd_ecom_color_main`* - color tint for icons, header and submit button
gradient start color

*`wd_ecom_color_main_light`* - header and submit button gradient end
color

*`wd_ecom_color_main_alpha80`* - text input layout title color

*`wd_ecom_color_toolbar_text`* - toolbar text and back arrow tint

*`wd_ecom_color_pay_button_text`* - pay button text color

*`wd_ecom_color_main_background`* - background color for main view

*`wd_ecom_color_error`* - used for all text input layouts to modify
error text color including the edit text line

==== Changing Fonts

To change fonts, override the font path to in string resources with name
`sdkpay_fontPath': e.g. strings.xml

....
    <string name="sdkpay_fontPath">fonts/myFont.otf</string>
....

==== Changing Text Size

To change the text size use dimensional attribute `wd_ecom_text_size`.
This affects all the modules, except `cardField`.

==== Customizing WIRETRANSFER Payments

[.image]##

*Color Resources*

1 - `wd_ecom_color_main`

2 - `wd_ecom_color_light`

3 - `wd_ecom_color_main_alpha80`

4 - `wd_ecom_color_pay_button_text`

5 - `wd_ecom_color_toolbar_text`

6 - `wd_ecom_color_error`

7 - `wd_ecom_color_main_background`

*Icons*

8 - `wd_ecom_arrow_back`

9 - `wd_ecom_cardholder_name`

10 - `wd_ecom_iban_3`

11 - `wd_ecom_camera_blue`