[#MobilePaymentSDK_IntegrationGuides]
---
== Mobile Payment SDK
---
[#MobilePaymentSDK_FirstSteps]
=== First Steps
---
Before you start coding, you are going to need some credentials:

. Merchant Account ID - the ID of your merchant account that will be
used to process transactions
. Secret Key - a value that you will use to create unique security
signatures for your transactions

//-

[NOTE]
====
You can find testing credentials under each payment method in REST API -> Test Credentials at https://docs.getneteurope.com/PaymentMethods.html[link]

Your account needs to be configured through Merchant Support to process mobile SDK payments.
====

Get your own credentials by contacting <<ContactUs, Merchant Support>>.

Below the supported locations the Mobile Payment SDK can connect to are listed. Both testing and production environments are available.

At the moment, the supported locations are as:

|===
| Gateway  | Hostname

| Production   | ``\https://api.getneteurope.com/``               
| Test         | ``\https://api-test.getneteurope.com/`` 
|
|===