[#Imprint]
== Imprint

*1.PagoNxt Merchant Solutions, S.L. – German Branch* +
Einsteinring 35 | 85609 Aschheim | Germany +
*Register Number*: AG München | HRB 261793 +
VAT ID: DE 339 882 217 +
 
Permanent Representatives: +
Anna Maria Werner and Beatriz Retamar Gomez 

Phone: +49 (0) 8920195380 +
E-Mail: connect@getneteurope.com

*Branch office of PagoNxt Merchant Solutions, S.L.* +
(Limited liability Company under Spanish law) +
Registered office of the company: Avenida Cantabria, s/n -Pampa PO, +
Boadilla del Monte/Madrid, Spain +
*Register Number PagoNxt Merchant Solutions, S.L*: Registro Mercantil de Madrid 087694410

*Managing Board:* +
-	Hector Blas Grisi Checa, (Chairman) +
-	Javier San Felix Garcia +
-	Dirk  Ludwig Marzluf +
-	Carlos Rey de Vicente +
-	Ignacio Narvarte Ichazo +
-	Maria del Mar Ruiz Andújar +
 
Register Number: Registro Mercantil de Madrid 087694410 +


*2.Santander Espana Merchant Services, Entidad de Pago, S.L.U.* +
Calle Juan Ignacio Luca de Tena 11 | 28027 Madrid | Spain +
*Registered in the Register of Institutions of the Bank of Spain:  6858* +
Tax Identification Number: B86621620
 
*Managing Director*: Ruben Justel Miranda 

Phone: +49 (0) 89 20195380

E-Mail: connect@getneteurope.com
