[#PPD_{payment-page-v2-anchor}-Manager]
== Manage your Themes and Translations

Use the {payment-page-v2-abbr} design manager menu to edit and organize your <<PPD_customize_save,themes>> and translations.

. Open the https://designer-test.{domain}[Payment Page Designer]. 
. Click *Login*.
. Use your credentials provided by <<ContactUs, Merchant Support>> to access the {payment-page-v2-abbr} design manager menu.

//-

WARNING: Make sure that only one user is editing a theme. If two users edit a theme at the same time, some changes might get lost.

NOTE: A session timeout requires a relogin to the {payment-page-v2-abbr} design manager menu after 60 minutes of inactivity.

The {payment-page-v2-abbr} design manager menu is divided into two sections:

* *Translations*
* *Themes*

[#PPD_{payment-page-v2-anchor}-Manager_Translations]
.Translations

Expand the *Translations* section to: 

* Import a translation file. The translation file must be available in .json format. +
* Export the default translation file. The default translation file is exported to a .json file.
+
NOTE: Edit the default translation file and import it as a new translation file.
+
* Edit imported translations. +
** Edit the translation file name. Double-click the file name or click the *Edit* button. +
** Edit the translations. Click *Export* to export the translations to a .json file. +
** Delete the translation file.

//-

You can modify the translations to e.g.:

* Meet local variations such as US or UK English. +
* Change button names.

//-

NOTE: You can only edit the languages available in the default translation file. You cannot add further languages.

[#PPD_{payment-page-v2-anchor}-Manager_Themes]
.Themes

Expand the *Themes* section to:

* Create a <<PPD_customize, new theme>>. +
* Import a theme. The theme file must be available in .json format. +
* Edit a theme. +
* Set the default theme. +
* Delete a theme. +

//-

NOTE: Click the *Theme preview* button on the right of the theme name to see a preview. The theme is displayed as a .jpg and can be downloaded.

.Imported Themes 
Click the theme name to expand the theme's properties to:

* Edit the theme name. Double-click the theme name or click the *Edit* button. 
* Select a <<PPD_{payment-page-v2-anchor}-Manager_Translations, translation file>>. 
* Set the theme as default. The default theme is used for payment processes if not indicated otherwise <<PPD_{payment-page-v2-anchor}-Manager_Sample, in the request>>. +
+
NOTE: The default theme can be identified by the asterisk symbol.
+
* Activate or deactivate the theme. Only activated themes can be used in the request. +
+
NOTE: Active themes can be identified by the tick symbol.
+
* Change the theme settings. Click *Style it* to open the theme in the <<PPD_customize_menu, Payment Page Designer>> menu.
+
NOTE: You can toggle between the Payment Page Designer and the {payment-page-v2-abbr} design manager menu. Use *BACK TO DESIGNER* to switch to the Payment Page Designer menu. Use *MANAGE* in the Payment Page Designer menu to return to the {payment-page-v2-abbr} design manager menu.
If *Style it* is unavailable in the {payment-page-v2-abbr} design manager menu, the theme is already open in the Payment Page Designer menu. 
+
* Save your changes. *Save* is available only if changes have been made.
* Export the theme to a .json file.
* Delete the theme.

//-

[#PPD_{payment-page-v2-anchor}-Manager_Field]
.Include a Theme in the Request

[%autowidth]
|===
| Field Name | Data Type | JSON Parent | Description

| theme | String | options ({ }) | The name of the PPD theme used for a specific payment process.
|===


[#PPD_{payment-page-v2-anchor}-Manager_Sample]
.Sample Request

[source,json,subs=attributes+]
----
include::{root}/samples/json/PaymentPageDesignerUsingThemes_AnExampleRequestWTheme.json[]
----

//-