[#RestApi_Samples]
== Samples

[#RestApi_Samples_All]
=== For All Payment Methods

[#RestApi_Samples_All_Xml]
==== XML
.XML Purchase Request (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_request_success_5ee0e0.xml[]
----

.XML Purchase Response (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_response_success_4529c7.xml[]
----

[#RestApi_Samples_All_Json]
==== JSON

.JSON Purchase Request (Successful)
[source,json,subs=attributes+]
----
include::{root}/samples/json/RestApiSamplesAllJson_JSON_PurchaseRequestSuccessful.json[]
----

.JSON Purchase Response (Successful)
[source,json,subs=attributes+]
----
include::{root}/samples/json/RestApiSamplesAllJson_JSON_PurchaseResponseSuccessful.json[]
----

[#RestApi_Samples_CreditCardOnly]
=== Credit Card Only

[#RestApi_Samples_CreditCardOnly_Transaction]
==== Transaction Simulation

.XML Purchase Request (Failure)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_request_failure.xml[]
----

.XML Purchase Response (Failure)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_response_failure_d1b701.xml[]
----

[#RestApi_Samples_CreditCardOnly_Timeout]
==== Timeout Simulation

The following request shows a transaction status simulation for a
successful credit card transaction that responded after 60,000
milliseconds.

.XML Purchase Timeout Simulation Request (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_request_success_3ff4d4.xml[]
----

.XML Purchase Timeout Simulation Response (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_response_success_7110a3.xml[]
----

[#RestApi_Samples_CreditCardOnly_ReferencedTransaction]
==== Referenced Transaction Simulation

.XML Initial Zero Dollar Authorization Request (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_authorization-only_request_success_916550.xml[]
----

.XML Initial Zero Dollar Authorization Response (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_authorization_response_success_5874c5.xml[]
----

.XML Following Purchase Request (Failure)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/RestApiSamplesCreditCardOnlyReferencedTransaction_FollowingPurchaseRequestFailure.xml[]
----

.XML Following Purchase Response (Failure)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_purchase_response_failure_b56251.xml[]
----

//-
