[#GeneralIntegrationOptions]
== Integration Options

There are multiple integration options available for {payment-gateway}.

[NOTE]
====
- The integration via *Payment Page* is described under <<GeneralIntegrationOptions_PP, Payment Page>>.
- For (near) real-time processing the *backend* implementation is
described under <<RestApi, REST API>>. However, the description of payment methods, for example, 
is common for both Payment Page and REST API.

//-
====

[#GeneralIntegrationOptions_PP]
[discrete]
=== Payment Page

Payment Page stands for secure, flexible, easy and
transparent payment processing. 

It provides all payment methods and
related options in one solution: Credit Card (with/without 3D
secure), SEPA, online banking payments, alternative
payment methods, and industry-specific solutions.

It handles the payment method selection as well as the collection
of payment details or consumer redirects to alternative payment provider
sites. With this solution, the merchant is only required to conform to a
limited PCI scope (self-questionnaire A).

Payment Page is available in three formats:

- Hosted Payment Page (HPP): The consumer is redirected to
{payment-gateway} to finish the checkout process.
- Embedded Payment Page (EPP): The payment screen is displayed in
overlay directly on the merchant's checkout page.
- Seamless integration:  The merchant's checkout page is incorporated
into {payment-provider-name}'s payment form. This solution provides a seamless shopping
experience for web-shoppers.
//-

NOTE: Only HTML knowledge is required for Payment Page integration.

[#GeneralIntegrationOptions_RestApi]
[discrete]
=== REST API

When merchants want full control over the checkout and payment process
they can create requests themselves and send them directly to the
_REST API_. All communications between a merchant and the REST API
are secured by TLS encryption (HTTPS).

Integration is possible by:

- XML requests sent from merchant's backend (server-to-server)
- JSON respectively
//-

NOTE: For the integration of {payment-gateway} via REST API, advanced programming skills are required.

PCI certified merchants can use {payment-gateway} without any restrictions.

Non PCI certified merchants can use _{payment-gateway}_ only with
referenced or recurring transactions. For initial transactions they must use a front end solution (e.g. <<PP, HPP>>).

Details to integrate _{payment-gateway}_ via REST API are
described <<RestApi, here>>.
