[#GeneralIntegrationOptions]
== Integration Options

There are multiple integration options available for {payment-gateway}.

[NOTE]
====
- The integration via *Payment Page* is described under <<GeneralIntegrationOptions_PP, Payment Page>>.
- For (near) real-time processing the *backend* implementation is
described under <<RestApi, REST API>>. However, the description of payment methods, for example, 
is common for both Payment Page and REST API.
- Processing of multiple transactions using *batches* is described under
<<BatchProcessingApi, Batch Processing API>>, available for both SEPA Direct Debit and SEPA Credit Transfer.
- Our *Payment SDK* offers a seamless user experience by rendering a payment form as an integral part of the merchant's mobile application.

//-
====

[#GeneralIntegrationOptions_PP]
[discrete]
=== Payment Page

{payment-provider-name} Payment Page stands for secure, flexible, easy and
transparent payment processing. 

It provides all payment methods and
related options in one solution: Credit Card (with/without 3D
secure), SEPA, online banking payments, mobile payments, alternative
payment methods, and industry-specific solutions.

It handles the payment method selection as well as the collection
of payment details or consumer redirects to alternative payment provider
sites. With this solution, the merchant is only required to conform to a
limited PCI scope (self-questionnaire A).

{payment-provider-name} Payment Page is available in three formats:

- Hosted Payment Page (HPP): The consumer is redirected to
{payment-gateway} to finish the checkout process.
- Embedded Payment Page (EPP): The payment screen is displayed in
overlay directly on the merchant's checkout page.
- Seamless integration:  The merchant's checkout page is incorporated
into {payment-provider-name}'s payment form. This solution provides a seamless shopping
experience for web-shoppers.
//-

NOTE: Only HTML knowledge is required for {payment-provider-name} Payment Page integration.

[#GeneralIntegrationOptions_RestApi]
[discrete]
=== REST API

When merchants want full control over the checkout and payment process
they can create requests themselves and send them directly to the
_REST API_. All communications between a merchant and the REST API
are secured by TLS encryption (HTTPS).

Integration is possible by:

- XML requests sent from merchant's backend (server-to-server)
- JSON respectively
- NVP (for credit card only)
//-

NOTE: For the integration of {payment-gateway} via REST API, advanced programming skills are required.

PCI certified merchants can use {payment-gateway} without any restrictions.

Non PCI certified merchants can use _{payment-gateway}_ only with
referenced or recurring transactions. For initial transactions they must use a front end solution (e.g. <<PP, HPP>>).

Details to integrate _{payment-gateway}_ via REST API are
described <<RestApi, here>>.

[#GeneralIntegrationOptions_Batch]
[discrete]
=== Batch Processing API

In order to process multiple transactions at the same time, {payment-provider-name}'s Batch Processing is the ideal solution for both fast and easy to
implement offline bulk transaction processing.

Batch processing is possible for the following payment methods:

- SEPA Direct Debit
- SEPA Credit Transfer
- Credit Card

//-

NOTE: Working programming knowledge is required to integrate this way.


[#GeneralIntegrationOptions_SDK]
[discrete]
=== SDK

The Software Development Kit (SDK) serves as a wrapper for the {payment-gateway} with a PCI V3 compliant native mobile payment
form. SDK is naturally developed for the integration into a merchant's
app as a software library where it covers sending payment requests to
the {payment-gateway}. It uses REST requests constructed by the merchant
sent over HTTPS protocol to {payment-gateway}
end-point where the REST API is exposed.

The following payment methods are currently supported:

- Credit Card
- PayPal
- SEPA Direct Debit
- Apple Pay
- Google Pay™
//-

Operation system interfaces:

- iOS
- Android
//-

NOTE: Working programmer knowledge is required to integrate this way.

//-
