[#GeneralIntegrationOptions]
== Integration Options

There are multiple integration options available for {payment-gateway}.

[NOTE]
====
- The integration via *Payment Page* is described under <<GeneralIntegrationOptions_PP, Payment Page>>.
- For (near) real-time processing the *backend* implementation is
described under <<RestApi, REST API>>. However, the description of payment methods, for example, 
is common for both Payment Page and REST API.

//-
====

[NOTE]
====
- Connections to our test and production web sites and services must not be locked on target IP address. The IP addresses of our services will become dynamic, therefore usage of FQDN or URL-based filtering for outgoing connections would be adequate.
 
- New digital certificates will be issued and applied on our applications. If your applications use certificate pinning, TLS connections will generate encryption errors. We advise against certificate pinning in general as a practice and kindly ask to allow the new certificates coming from our side.
 
- The digital certificates behind our servers will require the usage of SNI (Server Name Indication) feature for which we kindly ask you to make sure that it is activated. Without this option enabled on the client side, TLS encrypted connections may end up with errors. As the Akamai Web Application Firewall (WAF) is a cloud based service, our applications will dynamically resolve in their DNS names therefore the SNI TLS extension is required to be enabled.
 
- Customer side applications using HTTP request headers bigger than 32Kbytes will encounter connection errors. As of industry practices, even 16Kbytes is sufficient and we kindly ask to implement this limit. Nevertheless, if your applications require more, kindly contact us for this matter.


//-
====
[#GeneralIntegrationOptions_PP]
[discrete]
=== Payment Page

Payment Page stands for secure, flexible, easy and
transparent payment processing. 

It provides all payment methods and
related options in one solution: Credit Card (with 3D
secure), SEPA, online banking payments, alternative
payment methods, and industry-specific solutions.

It handles the payment method selection as well as the collection
of payment details or consumer redirects to alternative payment provider
sites. With this solution, the merchant is only required to conform to a
limited PCI scope (self-questionnaire A).

Payment Page is available in three formats:

- Hosted Payment Page (HPP): The consumer is redirected to
{payment-gateway} to finish the checkout process.
- Embedded Payment Page (EPP): The payment screen is displayed in
overlay directly on the merchant's checkout page.
- Seamless integration:  The merchant's checkout page is incorporated
into our payment form. This solution provides a seamless shopping
experience for web-shoppers.
//-

NOTE: Only HTML knowledge is required for Payment Page integration.

[#GeneralIntegrationOptions_RestApi]
[discrete]
=== REST API

When merchants want full control over the checkout and payment process
they can create requests themselves and send them directly to the
_REST API_. All communications between a merchant and the REST API
are secured by TLS encryption (HTTPS).

Integration is possible by:

- XML requests sent from merchant's backend (server-to-server)
- JSON respectively
//-

NOTE: For the integration of {payment-gateway} via REST API, advanced programming skills are required.

PCI certified merchants can use {payment-gateway} without any restrictions.

Non PCI certified merchants can use _{payment-gateway}_ only with
referenced or recurring transactions. For initial transactions they must use a front end solution (e.g. <<PP, HPP>>).

Details to integrate _{payment-gateway}_ via REST API are
described <<RestApi, here>>.
//-
