:payment-method-name: Klarna Payments

[#PPv2_Klarna]
== {payment-page-v2}

include::{root}/include/ppv2-general-information.adoc[]

Below, we provide a sample request for the available transaction type <<PPv2_Klarna_TransactionType_authorization, authorization>>, including a field list with short descriptions.

Below, we provide a field list with short descriptions.

For more details on the ``redirect-url``, see the 
<<PPSolutions_PPv2_ConfigureRedirects, Configuring Redirects and IPNs for {payment-page-v2-abbr}>> 
section.

For response verification examples, see
the <<PPSolutions_PPv2_PPv2Security, {payment-page-v2-abbr} Security>> section.

//include::{root}/include/ppv2-general-information-2.adoc[]

[#PPv2_Klarna_About]
=== About _{payment-method-name}_

_{payment-method-name}_ offer 3 payment options for consumers to pay when and how they prefer to: 

* **Pay now:** +
    - Quick and easy direct payments with 
        ** direct debit +
        payment-method name: ``klarna-debit``
        ** bank transfer +
        payment-method name: ``klarna-transfer``.
    - Support for recurring payments and subscriptions.
    - Type of <<PaymentMethods_PaymentMode_OnlineBankTransfer, Online Bank Transfer>>.
* **Pay later:**
    - Payment on invoice. Consumers pay for goods or services 14 - 60 days after receipt. 
    - payment-method name: ``klarna-paylater``
    - Type of <<PaymentMethods_PaymentMode_OfflineBankTransfer, Offline Bank Transfer>>.
* **Financing (Slice it):** +
    - Consumers pay for received goods or services in equal monthly installments.
    - payment-method name: ``klarna-finance``
    - Type of <<PaymentMethods_PaymentMode_OfflineBankTransfer, Offline Bank Transfer>>.

//-

_Klarna_ <<Klarnav2_reconciliation, takes full credit and fraud risk and guarantees payments>>.

[#PPv2_Klarna_CountriesCurrencies]
=== Countries and Currencies 

[%autowidth]
[cols="h,"]
|===
|Countries |Austria, Denmark, Finland, Germany, Netherlands, Norway, Sweden, Switzerland, UK
|Currencies | DKK, EUR, GBP, NOK, SEK
|===

[#PPv2_Klarna_TransactionType_authorization]
=== Transaction Type _authorization_

With _{payment-method-name}_ you can use the transaction types _authorization_ and _auto-sale_ which both trigger an _authorization_.

An _authorization_ reserves the specified amount from the account holder’s bank account for a later transfer. It performs an order risk check and an order reservation. Once an order is reserved, the payment is guaranteed.

[#PPv2_Klarna_TestCredentials]
=== Test Credentials

[cols="20h,80"]
|===
|URL (Endpoint)
|``\https://{pp-test-endpoint}``

|Merchant{nbsp}Account{nbsp}ID (MAID)
| f570c123-62f1-4a0d-8688-d999a05d50d4

|Username
| 16390-testing

|Password
| 3!3013=D3fD8X7

|===

[#PPv2_Klarna_Samples]
=== Sample Workflow
====
*For a successful transaction:*

. Create a payment session (initial request).
. Redirect the consumer to the payment page (initial response URL).
. Highly recommended: Parse and process the payment response.

//-
====

We provide JSON examples for each step of this process. You can find them below.

.Request Headers
[cols="20h,80"]
|===
|Authorization
a| Use username and password as given in your {payment-provider-name} contract to base64-encode the authorization.

For example for `user:password` the authorization header is:
[source,subs=attributes+]
----
Authorization: Basic dXNlcjpwYXNzd29yZA==
----
|Content-Type
a|
For JSON requests the content type header is:
[source,subs=attributes+]
----
Content-Type: application/json;charset=UTF-8
----
|===


[#PPv2_Klarna_TransactionType_auth_Create]
.1. Create a Payment Session (Initial Request)

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_KlarnaV2_AuthorizationRequest.json[]
----

[%autowidth]
[cols="m,,,,,,,"]
|===
4+s|Field (JSON) s|Data Type s|Mandatory/ +
Optional s|Size s|Description

|merchant-account-id 3+m|value |String |Mandatory |36 |A unique identifier assigned
to every merchant account (by {payment-provider-name}).
4+|request-id |String |Mandatory |150 a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

4+|transaction-type |String |Mandatory |30 a|The requested transaction type. Available transaction types for _{payment-method-name}_:

- `authorization`
- `auto-sale`

Both trigger an `authorization`.
//-

.2+|requested-amount  
3+m|[[PPv2_Klarna_Fields_requestedAmount_currency]]currency |String |Mandatory |3 a|The <<PPv2_Klarna_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.
3+m|value |Numeric |Mandatory |18.3 a|The full amount that is requested/contested in a transaction. The number of decimal places depends on the currency. +
The requested amount must be equal to the total amount of all order items.

Use ``.`` (decimal point) as separator.

.11+|account-holder 3+m|date-of-birth |String |Optional |n/a |Consumer's date of birth. +
Format: _Klarna_ accepts only ``dd-MM-YYYY`` or ``YYYY-MM-dd``. + 
If you provide a different format, _Klarna_ prompts the consumer to enter their birth date during the payment process.

3+m|first-name |String |Optional |32 |Consumer's first name.

3+m|last-name |String |Optional |32 |Consumer's last name.

3+m|email |String |Optional |64 |Consumer's email address.

3+m|gender |String |Optional |1 |Consumer's gender.

3+m|phone |String |Mandatory |32 |Consumer's phone number. +
Phone numbers need to be validated. Click <<PPv2_Klarna_phoneNumberValidation, here>> for details.

.5+m|address 2+m|street1 |String |Optional |128 |Street of the consumer's address.

2+|street2	|String |Optional |128 |House number of the consumer's address.	 

2+|city |String |Optional |32 |City of the consumer's address.

2+|country |String |Mandatory |3 |Country code of the consumer's address.

2+|postal-code |String |Optional |16 |Postal/ZIP code of the consumer's address.

.10+|shipping 3+m|first-name |String |Optional |32 |First name of the recipient.  
3+|last-name |String |Optional |32 |Last name of the recipient.

3+|email |String |Optional |64 | Email address of the recipient.	

3+|phone |String |Mandatory |32 |The phone number of the recipient. +
Phone numbers need to be validated. Click <<PPv2_Klarna_phoneNumberValidation, here>> for details.

.6+m|address 2+m|street1 |String |Optional |128 |Street of the recipient's address.

2+|street2 |String |Optional |128 |House number of the recipient's address.	 

2+|house-extension |String |Optional |32 |House extension of the recipient's address.	 

2+|city |String |Optional |32 |City of the recipient's address.

2+|country |String |Optional |3 |Country code of the recipient's address.

2+|postal-code |String |Optional |16 |Postal/ZIP code of the recipient's address.

4+|order-number	|String |Optional |255 |Order number of the merchant. +
If set, it shows as "order number" on _Klarna's_ confirmation page.

4+|locale	|String |Mandatory |2 |A 2-letter code which indicates what language
the payment page is rendered in (ISO 639-1).

.10+|order-items .10+m|order-item 2+m|quantity |Numeric |Mandatory |n/a  |Total number of this item in the shopping basket.

2+m|description |String |Optional |1024 |Description of the item in the shopping basket.

2+m|article-number |String |Optional |256 |EAN or other merchant-side article identifier.

2+m|name |String |Mandatory |256 |Name of the item in the shopping basket.

.2+m|amount m|value |Numeric |Mandatory |18.3 |Item’s price per unit.  +

Use ``.`` (decimal point) as separator.

|currency |String |Mandatory |3 |<<PPv2_Klarna_CountriesCurrencies, Currency>> of this item's price. Must match the <<PPv2_Klarna_Fields_requestedAmount_currency, order currency (requested amount currency)>>. +
Format: 3-character abbreviation according to ISO 4217.

2+|tax-rate |Numeric |Optional |5.2 a|Item’s tax rate per unit in percent. +
*Mandatory* if ``tax-amount`` is specified.

2+|tax-amount |Numeric |Optional |5.2 a|Item’s tax value per unit. +
*Mandatory* if ``tax-rate`` is specified.

2+|discount	|Numeric |Optional	|18.3 |The discount value for one order item.  +
Use ``.`` (decimal point) as separator.

2+|type	|String |Optional |n/a a|Order item type. +
Possible values: 

  - ``shipment_fee``
  - ``handling_fee``
  - ``discount``
  - ``physical``
  - ``sales_tax``
  - ``digital``
  - ``gift_card``
  - ``store_credit``

//-

If not specified, ``type`` is treated as a regular article.

4+|notification-url |String |Optional |256|The URL to which _{payment-gateway}_ sends the transaction outcome.

4+|success-redirect-url |String |Mandatory |2000 a|The URL to which the consumer
is redirected after a successful payment,
e.g. ``\https://{pp-redirect-url-success}``
4+|fail-redirect-url |String |Mandatory |2000 a|The URL to which the consumer is
redirected after a failed payment,
e.g. ``\https://{pp-redirect-url-error}``
4+|cancel-redirect-url |String |Mandatory |2000 a|The URL to which the consumer
is redirected after having canceled a payment,
e.g. ``\https://{pp-redirect-url-cancel}``

|payment-methods 2+m|payment-method m|name |String |Mandatory |15 a|The name of the payment method used for the transaction. 

Possible values: 

  - ``klarna-finance`` for payment in installments (Financing/Slice it)
  - ``klarna-debit`` for Klarna direct debit (Pay now) 
  - ``klarna-transfer`` for Klarna bank transfer (Pay now)
  - ``klarna-paylater`` for Klarna payment on invoice (Pay later)
//-

|===

[#PPv2_Klarna_phoneNumberValidation]
.Phone Number Validation

Both the consumer's phone number and the
phone number that corresponds to the shipping address are mandatory. +

include::{root}/include/Klarna-phoneNumberValidation.adoc[]

[#PPv2_Klarna_TransactionType_auth_Redirect]
.2. Redirect the Consumer to the Payment Page (Sample Response URL)

[source,json,subs=attributes+]
----
{
  "payment-redirect-url": "https://{pp-test-instance-hostname}/?wPaymentToken=nbuphpxyYFjdXwNY46kfeqa8Zt0ZWPkMmDTa0_wwP-4"
}
----
 
[%autowidth, cols="m,,"]
|===
| Field (JSON) | Data Type | Description

|payment-redirect-url 
|String 
|The URL which redirects to the payment
form. Sent as a response to the initial request.
|===

include::{root}/include/ppv2-redirect-instructions.adoc[]

[#PPv2_Klarna_TransactionType_auth_Response]
.3. Parse and Process the Payment Response (Decoded Payment Response)

[source,json,subs=attributes+]
----
include::{root}/samples/json/WPP_KlarnaV2_AuthorizationResponse.json[]
----
 
In addition to the request fields, the response returns the following fields:

[%autowidth, cols="m,,,,"]
|===
3+| Field (JSON) | Data Type | Description

3+|transaction-id 
|String 
|A unique identifier assigned for every transaction. Used when searching for or referencing it later.

3+|transaction-state 
|String 
a|The current transaction state. +
Possible values:

- ``in-progress``
- ``success``
- ``failed``

//-

Typically, a transaction starts with state ``in-progress`` and finishes with state either ``success`` or ``failed``. This information is returned in the response only.

3+m|completion-time-stamp
|Timestamp
|The UTC/ISO timestamp documents the time and date when the transaction was executed. +
Format: ``YYYY-MM-DDThh:mm:ss`` (ISO).

.6+|statuses .6+m|status 
m|description 
|String 
|The description of the transaction status message.

|severity    
|String 
a|The definition of the status message. Possible values:

- ``information``
- ``warning``
- ``error``

//-

|code 
|String 
|Status code of the status message.

|provider-code 
|String 
|Original _Klarna_ error code.

|provider-message 
|String 
|Error message to be shown to the consumer as required by _Klarna_.

|provider-transaction-id 
|String 
|_Klarna_ reservation number.

3+|api-id       
|String 
|Identifier of the currently used API.
|===

[#PPv2_Klarna_PostProcessing]
=== Post-Processing Operations 

{payment-page-v2-abbr} for _{payment-method-name}_ can be used for a first _authorization_ in a chain of recurring transactions. However, when it comes to referencing a transaction for any kind of post-processing operation - such as a _capture_ or _void_ of one of your _authorization_ transactions - use our <<RestApi, REST API>> directly.

IMPORTANT: Check the REST API <<KlarnaV2, _{payment-method-name}_ specification>> for details on post-processing operations for {payment-method-name}.

//[#PPv2_Klarna_JSONFields]
//include::{root}/include/ppv2-apm-optional-fields.adoc[]
//
//[#PPv2_Klarna_JSONNVPReference]
//include::{root}/include/ppv2-apm-json-nvp-reference.adoc[]

//-
