name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN_PATH: 'toolchain'

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Extract build name
      shell: bash
      run: echo "::set-output name=build_name::$(bash .scripts/extract_build_name.sh)"
      id: extract

    - name: Setup Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'

    - name: Bundle install
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 16 --retry 30

    - name: Build
      run: |
        bundle exec rake docs:all
        cp -r /tmp/build/html public/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GithubActions
        role-duration-seconds: 1200

    - name: Deploy to S3
      run: bash .scripts/deploy.sh
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PUBLIC_GN }}
        AWS_S3_FOLDER: ${{ secrets.AWS_S3_BUCKET_FOLDER_GN }}
        AWS_CF_DIST_ID: ${{ secrets.AWS_CF_DIST_ID_PUBLIC_GN }}

