:txTypeName: adjustAuthorization

[#Klarnav2_TransactionTypes_adjustAuthorization]
==== _adjust-authorization_

Use this transaction type to update a preceding _authorization_ or to add new information to it. 

You can update

* order amount.
* billing address.
* shipping address.

//-

[NOTE] 
====
* You can only adjust authorizations that have not yet been captured or canceled.
* Multiple updates are possible.
//-
====

For ``klarna-paylater``, the updated authorization amount can exceed the amount that has initially been authorized.
If the change of an _authorization_ increases the total order amount, _Klarna_ performs another risk check. A new risk check can lead to a rejection of the
authorization adjustment request. In this case, the initial _authorization_ is
still valid and can be updated, captured or canceled.

For ``klarna-debit``, ``klarna-transfer`` and ``klarna-finance``, the updated authorization amount must not exceed the amount that has been initially authorized.

To refer to a specific _authorization_ or _adjust-authorization_, you need the ``parent-transaction-id``, which is the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

[#KlarnaV2_TransactionTypes_adjustAuthorization_Workflow]
===== _adjust-authorization_ Workflow

image::images/Klarnav2_workflow_adjustAuthorization.svg[]

. -> Send an _adjust-authorization_ request. This request must contain the ``parent-transaction-id``. Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_ response.

. _{payment-gateway}_ updates the initial (or already adjusted) authorization and forwards the request to _Klarna_. 
. _Klarna_ updates order amount and/or address and returns the result of the adjustment.
. _{payment-gateway}_ sends you the _adjust-authorization_ response which contains the status code. +
+
[NOTE]
====
If your adjust-authorization request does not change the preceding authorization, the response indicates this with two statuses:

. <status code="201.0000" description="guaranteed:The resource was successfully created." severity="information"/>
. <status code="201.1150" description="Transaction already processed, no data has been updated." severity="information" provider-transaction-id="218d62d1-dc28-4e20-af84-2ba405cc949c"/>

//-
====
. -> Process the _adjust-authorization_ response.

//-

[#KlarnaV2_TransactionTypes_adjustAuthorization_Fields]
===== _adjust-authorization_ Fields

Fields can be mandatory (M) or optional (O).

[%autowidth, stripes=none]
[cols="m,,,,"]
|===
|Field |<<APIRef_FieldDefs_Cardinality, M/O>> |Data Type |Size |Description

|merchant-account-id 
|O 
|String 
|36 
|A unique identifier assigned
to every merchant account (by {payment-provider-name}).

|request-id 
|M
|String 
|150
a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

|transaction-type 
|M 
|String
|30 
|The requested transaction type. Set this field to `adjust-authorization`.

|parent-transaction-id
|M
|String 
|36
|Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

|requested-amount  
|M
|Numeric
|18.3
|Total order amount to be reserved. The number of decimal places depends on the currency. +
The requested amount must be equal to the sum of all order item amounts. +
For ``klarna-debit``, ``klarna-transfer`` and ``klarna-financing``, it must not exceed the amount of the preceding _authorization_. +
For ``klarna-paylater``, you may adjust the ``requested-amount`` to a higher value than the preceding authorization. 

Use ``.`` (decimal point) as separator.

|[[KlarnaV2_TransactionTypes_adjustAuthorization_Fields_requestedAmount_currency]]requested-amount@currency 
|M 
|String
|3 
a|The <<KlarnaV2_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.

|order-detail
|O
|String
|
|Description of update/change.

|order-number	
|O 
|String
|255 
|Order number as provided by merchant. +
If you send it, it shows as "order number" on _Klarna_'s payment confirmation page.

|parent-transaction-amount
|Response only
|String 
|18.3
|``requested-amount`` of the preceding _authorization_ or _adjust-authorization_.

|parent-transaction-amount@currency
|Response only
|String 
|3
|``requested-amount@currency`` of the preceding _authorization_ or _adjust-authorization_.

|locale	
|Response only 
|String
|5 
|A 5-letter code that indicates what <<KlarnaV2_Locales, language>> the payment page is rendered in (RFC 1766).

|transaction-id 
|Response only
|String
|36
|A unique identifier assigned for every transaction. Generated by {payment-provider-name}. Used when searching for or referencing it later.

|transaction-state 
|Response only
|String
|12
a|Transaction status. +
Possible values: 

  - ``success``
  - ``failed``

//-

|completion-time-stamp
|Response only
|DateTime
|
|The timestamp documents the time and date when the transaction was completed.

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_paymentMethod.adoc[tags=**;!mandatory;!MO;!recurring;!initialAuthorization]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_notifications.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolder.adoc[tags=**;!txTypes]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolderAddress.adoc[tags=**;!authorization]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_shipping.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_orderItems.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_status.adoc[]

|===

[#KlarnaV2_TransactionTypes_adjustAuthorization_Samples]
===== _adjust-authorization_ Samples

._adjust-authorization_ Request
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_adjustAuthorization_request.xml[]
----

NOTE: {{txnId}} serves as placeholder. Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

._adjust-authorization_ Response
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_adjustAuthorization_response.xml[]
----

:!txTypeName:

//-