:txTypeName: captureAuthorization

[#KlarnaV2_TransactionTypes_captureAuthorization]
==== _capture-authorization_

When the goods or services are ready to be delivered, you have to capture an authorized order fully or partially.

[NOTE]
====
*** You cannot add new articles.
*** You cannot change the price of the ordered items, otherwise the _capture-authorization_ transaction will be rejected.
*** Every partial capture triggers the creation and sending of a new payment instruction.

//-
====

Once an authorized amount is captured, the due date for payment is set. The
default payment due date is 14 days after capturing.

_Klarna_ pays you the order amount according to the agreed billing period.

To refer to a specific _authorization_, you need the ``parent-transaction-id``, which is the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_ response.

_Klarna_ sends *payment instructions* (containing bank account details) per email to your consumer.
//-

[#KlarnaV2_TransactionTypes_captureAuthorization_Workflow]
===== _capture-authorization_ Workflow

image::images/Klarnav2_workflow_captureAuthorization.svg[]

. -> Send an _capture-authorization_ request. This request must contain the ``parent-transaction-id``. Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_ response.

 ** If the _capture-authorization_
request does not contain order items, _{payment-gateway}_ captures the total order amount, i.e. all order items of the preceding _authorization_ transaction are captured and must be delivered.
  ** Multiple partial captures are possible by sending
_capture-authorization_ requests with order items to be captured.
. _{payment-gateway}_ forwards the request to _Klarna_. 
. _Klarna_ returns the capture result.
. _{payment-gateway}_ sends you the _capture-authorization_ response which contains the status code.
. -> Process the _capture-authorization_ response.

//-

[#KlarnaV2_TransactionTypes_captureAuthorization_Fields]
===== _capture-authorization_ Fields

Fields can be **M**andatory or **O**ptional.

[%autowidth,stripes=none]
[cols="m,,,,"]
|===
|Field |<<APIRef_FieldDefs_Cardinality, M/O>> |Data Type |Size |Description

|merchant-account-id 
|O 
|String 
|36 
|A unique identifier assigned to every merchant account (by {payment-provider-name}).

|request-id 
|M
|String 
|150 
a|A unique identifier assigned by the merchant
to each request. Used when searching for or referencing it later.

As the request ID must be unique, ``{{$guid}}`` serves as a placeholder; Postman
uses it to generate a random ``request-id`` for testing.

Allowed characters:  ``[a-z0-9-\_]``.

|transaction-type 
|M 
|String
|30 
|The requested transaction type. Set this field to `capture-authorization`.

|parent-transaction-id
|M
|String 
|36
|Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

|requested-amount  
|M
|Numeric
|18.3
a|Total order amount to be captured. The number of decimal places depends on the currency. 

The requested amount must be equal to the total amount of all order items.

The total amount of all _capture-authorization_ transactions must not exceed the amount of the preceding _authorization_ or _adjust-authorization_ transaction.

Use ``.`` (decimal point) as separator.

|[[KlarnaV2_TransactionTypes_captureAuthorization_Fields_requestedAmount_currency]]requested-amount@currency 
|M 
|String
|3 
a|The <<KlarnaV2_CountriesCurrencies, currency>> of the requested/contested
transaction amount. +
Format: 3-character abbreviation according to ISO 4217.

|order-detail
|O
|String
|
|Message or other important information for the consumer, shown on the
payment instructions. +
Requires a setting in your <<ContactUs, merchant configuration>>.

|order-number	
|Response only 
|String
|255 
|Order number of the merchant as sent in the preceding _authorization_, _adjust-authorization_. Shows as "order number" on _Klarna_'s payment confirmation page.

|parent-transaction-amount
|Response only
|String 
|18.3
|``requested-amount`` of the preceding _authorization_ or _adjust-authorization_.

|parent-transaction-amount@currency
|Response only
|String 
|3
|``requested-amount@currency`` of the preceding _authorization_ or _adjust-authorization_.

|locale	
|Response only 
|String
|5 
|A 5-letter code that indicates what <<KlarnaV2_Locales, language>> the payment page is rendered in (RFC 1766).

|transaction-id 
|Response only
|String
|36
|A unique identifier assigned for every transaction. Generated by {payment-provider-name}. Used when searching for or referencing it later.

|transaction-state 
|Response only
|String
|12
a|Transaction status. +
Possible values: 

  - ``success``
  - ``failed``

//-

|completion-time-stamp
|Response only
|DateTime
|
|The timestamp documents the time and date when the transaction was completed.

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_paymentMethod.adoc[tags=**;!mandatory;!MO;!recurring;!adjust-authorization;!initialAuthorization]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_notifications.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolder_responseOnly.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_accountHolderAddress_responseOnly.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_shipping_followUp.adoc[tags="**;!adjust-capture;capture-authorization"]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_orderItems.adoc[]

include::{root}/include/klarna-payments/fields/klarnaPayments_fields_status.adoc[]

|===

[#KlarnaV2_TransactionTypes_captureAuthorization_Samples]
===== _capture-authorization_ Samples

._capture-authorization_ Request
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_captureAuthorization_request.xml[]
----

NOTE: {{txnId}} serves as placeholder. Enter the ``transaction-id`` of the preceding _authorization_ or _adjust-authorization_.

._capture-authorization_ Response
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/Klarnav2_captureAuthorization_response.xml[]
----

:!txTypeName:

//-